#!/usr/bin/env bash
# Regenerates WALKTHROUGH.md by really running majordomus in a disposable repository.
# Usage: bash examples/minimal/generate.sh > examples/minimal/WALKTHROUGH.md
set -eu
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; MJ="$ROOT/bin/majordomus"
T="$(mktemp -d "${TMPDIR:-/tmp}/mj-example.XXXXXX")"; trap 'rm -rf "$T"' EXIT
cd "$T"; git init -q .; git config user.email dev@example.com; git config user.name dev
mkdir -p lib/auth test; echo 'callback = 1' > lib/auth/oauth.rb; echo 'ok' > test/oauth_test.rb
git add . && git commit -qm "initial" 
run() { local disp="$*"; disp="${disp//$MJ/majordomus}"; printf '\n```\n$ %s\n' "$disp"; "$@" 2>&1 | sed "s#$T#<repo>#g; s#$ROOT#<majordomus>#g" || true; printf '```\n'; }
cat <<'H'
# Walk-through: a scratch repository from `init` to `finish`

Generated by `examples/minimal/generate.sh`, which really runs the tool in a temporary
repository. Everything below is captured output; regenerate it rather than editing it.
H
printf '\n## 1. Install into the project\n'
run "$MJ" init
run "$MJ" update
printf '\n`doctor` says exactly what is still missing:\n'
run "$MJ" doctor
printf '\n## 2. Wire the two hooks it asked for\n'
printf '#!/bin/sh\n%s doctor || exit $?\n' "$MJ" > .git/hooks/pre-commit
printf '#!/bin/sh\n%s finish --check || exit $?\n' "$MJ" > .git/hooks/pre-push
chmod +x .git/hooks/pre-commit .git/hooks/pre-push
run "$MJ" doctor
git add -A >/dev/null; git -c core.hooksPath=/dev/null commit -qm "add majordomus" >/dev/null
printf '\n## 3. Start a scoped task\n'
run "$MJ" start "fix OAuth callback dropping state" --scope lib/auth,test/oauth_test.rb --profile debugging --owner alice
printf '\n## 4. Work, then check\n\nThe worker edits `lib/auth/oauth.rb` and also, by mistake, `test/other.rb`, which is outside the scope:\n'
echo 'callback = 2' > lib/auth/oauth.rb; echo 'x' > test/other.rb
run "$MJ" check
rm test/other.rb
printf '\nAfter removing the out-of-scope file:\n'
run "$MJ" check
printf '\n## 5. Try to finish too early\n'
run "$MJ" finish --outcome completed --verify-command "true"
printf '\n## 6. Hand over, resolve, finish\n'
printf '\n```\n$ printf "# Objective\\n...\\n# Current State\\n...\\n# Next Action\\n...\\n" | majordomus handover\n'
printf '# Objective\nStop the OAuth callback dropping the state parameter.\n# Current State\nRoot cause found in the proxy rewrite; fix applied in lib/auth/oauth.rb.\n# Next Action\nAdd the regression test and finish.\n' | "$MJ" handover | sed "s#$T#<repo>#g"; printf '```\n'
run "$MJ" handover --resolve
echo 'regression' >> test/oauth_test.rb
run "$MJ" finish --outcome completed --verify-command "true"
printf '\n## 7. What was recorded\n'
run cat .majordomus/state/current.yaml
printf '\n```\n$ tail -n 1 .majordomus/state/ledger.jsonl\n'; tail -n 1 .majordomus/state/ledger.jsonl | sed "s#$T#<repo>#g"; printf '```\n'
printf '\n## 8. Drift is visible\n\nSomeone edits the generated file by hand and changes the policy without regenerating:\n'
echo "my extra rule" >> AGENTS.md
sed -i.bak 's/checkpoint_interval_default: 15m/checkpoint_interval_default: 20m/' .majordomus/policy.yaml; rm -f .majordomus/policy.yaml.bak
run "$MJ" watch
run "$MJ" update
