//! The provider artifacts, rendered from the canonical deployment object: the container
//! image definition, the ignore file that bounds its build context, and the provider
//! configuration.
//!
//! None of the three is authoritative and none is written by hand. Each carries a header
//! naming the object it came from and the command that regenerates it, and
//! `majordomus generate --check` refuses a tree where one of them was edited. That is the
//! whole point of the kind: the port, the routes, the resources, the machine count and the
//! build inputs are stated once, and these files are views of that one statement.

use crate::generate::Artifact;

use super::Deployment;

/// Where the image definition goes.
pub const DOCKERFILE: &str = "deploy/Dockerfile";
/// Where the build context's ignore file goes. Docker reads it from the context root, so
/// it lives at the repository root whatever the image definition's own path is.
pub const DOCKERIGNORE: &str = ".dockerignore";
/// Where the provider configuration goes. Fly reads `fly.toml` from the working directory.
pub const FLY_TOML: &str = "fly.toml";

/// The Rust toolchain the builder stage pins. A floating tag would make the image a
/// different thing on different days, which is the opposite of what a deployment is for.
pub const RUST_IMAGE: &str = "rust:1.85-alpine3.21";
/// The runtime base, pinned for the same reason.
pub const RUNTIME_IMAGE: &str = "alpine:3.21";
/// The unprivileged user the deployed process runs as.
pub const RUN_USER: &str = "majordomus";
/// Where the layer and the tool distribution live inside the image.
pub const APP_DIR: &str = "/app";

/// The comment header every generated artifact carries: what wrote it, from what, and how
/// to change it. A contributor who edits the output is told which file to change instead.
fn header(comment: &str, source: &str, what: &str) -> String {
    format!(
        "{comment} {what}\n\
         {comment} GENERATED by `majordomus generate deployment` from {source}.\n\
         {comment} Do not edit: `majordomus generate --check` refuses a hand edit. Change\n\
         {comment} the deployment object and regenerate.\n\n"
    )
}

/// The directory of the package the builder stage compiles: the one input that is a build
/// input rather than something the running process reads.
fn package_dir(d: &Deployment) -> Option<&str> {
    d.build
        .inputs
        .iter()
        .map(String::as_str)
        .find(|p| p.rsplit('/').next() == Some(d.build.package.as_str()))
}

/// The inputs the running process reads: everything the build context carries except the
/// package the builder compiles.
fn runtime_inputs(d: &Deployment) -> Vec<&str> {
    let pkg = package_dir(d);
    d.build
        .inputs
        .iter()
        .map(String::as_str)
        .filter(|p| Some(*p) != pkg)
        .collect()
}

/// The container image, as a multi-stage build: a builder that holds the toolchain and a
/// runtime that holds the binary, the layer and nothing else. The runtime carries no
/// compiler, no cargo registry, no repository history and no shell history — what is not
/// copied in cannot leak out.
pub fn dockerfile(d: &Deployment, source: &str) -> String {
    let mut out = header("#", source, "The container image of this repository's deployment.");
    let pkg = package_dir(d).unwrap_or("apps");
    out.push_str(&format!(
        "FROM {RUST_IMAGE} AS build\n\
         RUN apk add --no-cache musl-dev\n\
         WORKDIR /src\n\
         COPY {pkg} ./{pkg}\n\
         RUN cargo build --locked --{profile} --manifest-path {pkg}/Cargo.toml --package {package} --bin {binary}\n\n",
        profile = d.build.profile,
        package = d.build.package,
        binary = d.build.binary,
    ));
    out.push_str(&format!(
        "FROM {RUNTIME_IMAGE}\n\
         # An unprivileged user, which is also why the declared port is above 1024.\n\
         RUN adduser -D -H -u 10001 {RUN_USER}\n\
         WORKDIR {APP_DIR}\n\
         COPY --from=build /src/{pkg}/target/{profile}/{binary} /usr/local/bin/{binary}\n",
        profile = d.build.profile,
        binary = d.build.binary,
    ));
    for input in runtime_inputs(d) {
        out.push_str(&format!("COPY {input} {APP_DIR}/{input}\n"));
    }
    out.push_str(&format!(
        "USER {RUN_USER}\n\
         EXPOSE {port}\n\
         # The address, the port and the interface are the object's; this command names the\n\
         # deployment and reads them from it. Discovery is a filesystem walk because the\n\
         # image carries the layer without the repository that tracks it.\n\
         ENTRYPOINT [\"{binary}\"]\n\
         CMD [\"serve\", \"--discovery\", \"filesystem\", \"--deployment\", \"{id}\"]\n",
        port = d.listen.port,
        binary = d.build.binary,
        id = d.id,
    ));
    out
}

/// The build context: nothing but the declared inputs. Everything is excluded and each
/// input is let back in, so a file that appears in the repository tomorrow does not appear
/// in the image tomorrow.
pub fn dockerignore(d: &Deployment, source: &str) -> String {
    let mut out = header(
        "#",
        source,
        "What the deployment's build context carries: only the declared inputs.",
    );
    out.push_str("*\n");
    for input in &d.build.inputs {
        out.push_str(&format!("!{input}\n"));
    }
    // The image definition is not an input of the deployment; it is a view of it. It is
    // let back in because a builder that reads the context needs the file it builds from.
    out.push_str(&format!("!{DOCKERFILE}\n"));
    out.push_str(
        "\n# and never these, wherever they appear inside an input\n\
         **/.git\n\
         **/target\n\
         **/node_modules\n\
         **/.DS_Store\n\
         .ai/local\n",
    );
    out
}

/// The provider configuration. Every value here is read from the object; nothing is stated
/// twice, and the `[build]` section points at the generated image definition.
pub fn fly_toml(d: &Deployment, source: &str) -> String {
    let mut out = header(
        "#",
        source,
        "The Fly.io configuration of this repository's deployment.",
    );
    out.push_str(&format!(
        "app = \"{app}\"\n\
         primary_region = \"{region}\"\n\n\
         [build]\n\
         dockerfile = \"{DOCKERFILE}\"\n\n\
         [http_service]\n\
         internal_port = {port}\n\
         force_https = {https}\n\
         auto_stop_machines = \"{stop}\"\n\
         auto_start_machines = {start}\n\
         min_machines_running = {min}\n\n",
        app = d.application,
        region = d.region,
        port = d.listen.port,
        https = d
            .provider
            .fly
            .as_ref()
            .and_then(|f| f.force_https)
            .unwrap_or(true),
        stop = if d.machines.autostop { "stop" } else { "off" },
        start = d.machines.autostart,
        min = d.machines.min_running,
    ));
    if let Some(c) = d.provider.fly.as_ref().and_then(|f| f.concurrency) {
        out.push_str(&format!(
            "  [http_service.concurrency]\n  type = \"requests\"\n  soft_limit = {}\n  hard_limit = {}\n\n",
            c.soft_limit, c.hard_limit
        ));
    }
    out.push_str(&format!(
        "  [[http_service.checks]]\n\
         \x20 grace_period = \"{grace}s\"\n\
         \x20 interval = \"{interval}s\"\n\
         \x20 method = \"GET\"\n\
         \x20 timeout = \"{timeout}s\"\n\
         \x20 path = \"{liveness}\"\n\n\
         \x20 [[http_service.checks]]\n\
         \x20 grace_period = \"{grace}s\"\n\
         \x20 interval = \"{interval}s\"\n\
         \x20 method = \"GET\"\n\
         \x20 timeout = \"{timeout}s\"\n\
         \x20 path = \"{readiness}\"\n\n",
        grace = d.health.grace_seconds.unwrap_or(2),
        interval = d.health.interval_seconds.map(|v| v.get()).unwrap_or(15),
        timeout = d.health.timeout_seconds.map(|v| v.get()).unwrap_or(2),
        liveness = d.health.liveness,
        readiness = d.health.readiness,
    ));
    out.push_str(&format!(
        "[[vm]]\n\
         cpu_kind = \"{kind}\"\n\
         cpus = {cpus}\n\
         memory_mb = {memory}\n",
        kind = match d.resources.cpu_kind {
            super::CpuKind::Shared => "shared",
            super::CpuKind::Performance => "performance",
        },
        cpus = d.resources.cpus,
        memory = d.resources.memory_mb,
    ));
    out
}

/// The three artifacts of one deployment.
pub fn artifacts(d: &Deployment, source: &str) -> Vec<Artifact> {
    vec![
        Artifact {
            path: DOCKERFILE.into(),
            content: dockerfile(d, source),
        },
        Artifact {
            path: DOCKERIGNORE.into(),
            content: dockerignore(d, source),
        },
        Artifact {
            path: FLY_TOML.into(),
            content: fly_toml(d, source),
        },
    ]
}
