//! The shell adapters: the only shell code in the completion, and it knows nothing.
//!
//! Each adapter below does four things — read the words being completed, find the cursor,
//! ask this executable, print what comes back. There is no command in them, no flag, no
//! identifier, no repository path and no version. That is the property that matters: a
//! command added tomorrow is completed by an adapter loaded a year ago, because the
//! adapter never learned the old set in the first place.
//!
//! # What a person installs, once
//!
//! ```sh
//! # ~/.zshrc
//! eval "$(majordomus completion init --shell zsh)"
//! ```
//!
//! One line, for every repository. The repository being completed is decided per
//! invocation by where the shell is, which is how one integration serves many checkouts
//! and how leaving a repository leaves nothing behind.
//!
//! # The text protocol
//!
//! One candidate per line, `value`, a tab, the description. Empty output means the engine
//! has nothing to offer, and the adapter falls back to the shell's own file completion —
//! which is what an argument that takes a path wants, and what an unknown command deserves.

/// The environment variable an adapter reads to find the executable, so that a checkout's
/// own launcher can be used without a second adapter.
pub const BIN_ENV: &str = "MAJORDOMUS_COMPLETION_BIN";

/// The zsh integration.
///
/// `compdef` is attached to the two spellings of this executable, to the shell tool, and to
/// the workflow runner. The runner's completion is the same function with a different
/// surface, which is the whole of the "no second completion implementation" property: one
/// query, one engine, one graph.
pub const ZSH: &str = r#"# majordomus — shell completion, generated by `majordomus completion init --shell zsh`.
# Carries no command, no flag and no identifier: every candidate comes from
# `majordomus completion query`, which answers from the command graph of the repository the
# shell is in. Load it once; it serves every repository.
_majordomus_query() {
  local surface="$1"
  local bin="${MAJORDOMUS_COMPLETION_BIN:-majordomus}"
  local -a lines items
  lines=("${(@f)$(command "$bin" completion query --surface "$surface" --format text --cursor "$((CURRENT-1))" -- "${words[@]}" 2>/dev/null)}")
  local line value description
  for line in "${lines[@]}"; do
    [[ -z "$line" ]] && continue
    value="${line%%	*}"
    description="${line#*	}"
    [[ "$description" == "$line" ]] && description=""
    items+=("${value}:${description}")
  done
  if (( ${#items} )); then
    _describe -t majordomus 'candidate' items
  else
    _files
  fi
}
_majordomus_complete() { _majordomus_query cli }
_majordomus_workflow_complete() { _majordomus_query workflow }
compdef _majordomus_complete majordomus
compdef _majordomus_complete majordomus-cli
compdef _majordomus_workflow_complete just
"#;

/// The bash integration.
pub const BASH: &str = r#"# majordomus — shell completion, generated by `majordomus completion init --shell bash`.
# Carries no command, no flag and no identifier: every candidate comes from
# `majordomus completion query`.
_majordomus_complete() {
  local surface=cli
  case "${COMP_WORDS[0]}" in just) surface=workflow ;; esac
  local bin="${MAJORDOMUS_COMPLETION_BIN:-majordomus}"
  local line value
  COMPREPLY=()
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    value="${line%%	*}"
    COMPREPLY+=("$value")
  done < <(command "$bin" completion query --surface "$surface" --format text --cursor "$COMP_CWORD" -- "${COMP_WORDS[@]}" 2>/dev/null)
  if [ ${#COMPREPLY[@]} -eq 0 ]; then
    while IFS= read -r line; do COMPREPLY+=("$line"); done < <(compgen -f -- "${COMP_WORDS[COMP_CWORD]}")
  fi
}
complete -F _majordomus_complete majordomus
complete -F _majordomus_complete majordomus-cli
complete -F _majordomus_complete just
"#;

/// The fish integration.
///
/// fish's own completion protocol is a value, a tab, a description — which is the text
/// protocol this engine already prints, so the adapter forwards the answer unaltered
/// rather than reformatting it.
pub const FISH: &str = r#"# majordomus — shell completion, generated by `majordomus completion init --shell fish`.
# Carries no command, no flag and no identifier: every candidate comes from
# `majordomus completion query`.
function __majordomus_complete
    set -l bin majordomus
    if set -q MAJORDOMUS_COMPLETION_BIN
        set bin $MAJORDOMUS_COMPLETION_BIN
    end
    set -l words (commandline -opc)
    set -l current (commandline -ct)
    set -l surface cli
    if test (count $words) -gt 0; and test $words[1] = just
        set surface workflow
    end
    command $bin completion query --surface $surface --format text --cursor (count $words) -- $words $current 2>/dev/null
end
complete -c majordomus -f -a '(__majordomus_complete)'
complete -c majordomus-cli -f -a '(__majordomus_complete)'
complete -c just -f -a '(__majordomus_complete)'
"#;

/// Every adapter, for a test that asserts the property they share.
pub const ALL: &[(&str, &str)] = &[("zsh", ZSH), ("bash", BASH), ("fish", FISH)];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command_graph::{build, Inputs};

    #[test]
    fn no_adapter_carries_a_command_name() {
        let graph = build(&Inputs::default());
        for (shell, script) in ALL {
            // The prose in an adapter explains what it is; the code is what could go
            // stale. Only the code is read.
            let code: String = script
                .lines()
                .filter(|l| !l.trim_start().starts_with('#'))
                .collect::<Vec<_>>()
                .join("\n");
            // The one command an adapter is allowed to name is the query it makes; every
            // other command word appearing here would be a set the adapter had learned.
            let code = code.replace("completion query", "");
            for node in &graph.commands {
                if node.id.as_str().starts_with("executable.completion") {
                    continue;
                }
                for word in node.path.iter().filter(|w| w.len() > 3) {
                    assert!(
                        !code.contains(&format!(" {word} ")),
                        "the {shell} adapter names the command word `{word}`"
                    );
                }
            }
        }
    }

    #[test]
    fn every_adapter_asks_the_same_question() {
        for (shell, script) in ALL {
            assert!(
                script.contains("completion query"),
                "the {shell} adapter does not ask"
            );
            assert!(
                script.contains(BIN_ENV),
                "the {shell} adapter cannot be pointed at a checkout's own launcher"
            );
            assert!(
                script.contains("--surface"),
                "the {shell} adapter does not say which surface it is completing"
            );
        }
    }
}
