. "$ROOT/test/lib.sh"
"$MJ" init >/dev/null
expect_exit 0 "$MJ" update
expect_grep '^create CLAUDE.md'
[ -f CLAUDE.md ] && [ -f AGENTS.md ] && [ -f GEMINI.md ] && [ ! -e .majordomus/generated ]
# the target describes itself: the stamp names the policy hash and the content hash
expect_grep '^<!-- generated by `majordomus update` from .* \(policy [0-9a-f]{12}, content [0-9a-f]{16}\) ' CLAUDE.md
expect_grep 'generated by `majordomus update`' CLAUDE.md
expect_grep '\| `debugging` \| strong \| high' CLAUDE.md
expect_grep 'scope respected' CLAUDE.md
expect_grep '`# Objective`, `# Current State`, `# Next Action`' CLAUDE.md
expect_no_grep '\{\{' CLAUDE.md
expect_grep '"event":"projections.updated"' .majordomus/state/ledger.jsonl
# deterministic: second run changes nothing
sha1=$(shasum -a 256 CLAUDE.md | cut -d' ' -f1)
expect_exit 0 "$MJ" update
expect_grep '^unchanged CLAUDE.md'
[ "$(shasum -a 256 CLAUDE.md | cut -d' ' -f1)" = "$sha1" ]
# doctor now only fails on wiring (10), not missing (12)
expect_exit 10 "$MJ" doctor
expect_grep 'OK +projection +CLAUDE.md — content matches its stamp'
expect_grep 'OK +budget'
# wire the hooks -> doctor healthy
cat > .git/hooks/pre-commit <<H
#!/bin/sh
$MJ doctor || exit \$?
H
cat > .git/hooks/pre-push <<H
#!/bin/sh
$MJ finish --check || exit \$?
H
chmod +x .git/hooks/pre-commit .git/hooks/pre-push
expect_exit 0 "$MJ" doctor
expect_grep 'doctor: 0 failure'
# a hook that swallows the exit code is not wired
printf '#!/bin/sh\n%s doctor || true\n' "$MJ" > .git/hooks/pre-commit
expect_exit 10 "$MJ" doctor
expect_grep 'swallows the exit code'
printf '#!/bin/sh\n%s doctor || exit $?\n' "$MJ" > .git/hooks/pre-commit
# hand edit: doctor flags it, update refuses, --diff shows it, --force restores
echo "my own rule" >> CLAUDE.md
expect_exit 10 "$MJ" doctor
expect_grep 'content differs from its own stamp'
expect_exit 15 "$MJ" update
expect_grep 'hand-edited'
expect_exit 0 "$MJ" update --diff CLAUDE.md
expect_grep '^-my own rule'
expect_exit 0 "$MJ" update --force
expect_no_grep 'my own rule' CLAUDE.md
expect_exit 0 "$MJ" doctor
# dry run writes nothing
sed -i.bak 's/checkpoint_interval_default: 15m/checkpoint_interval_default: 20m/' .majordomus/policy.yaml; rm -f .majordomus/policy.yaml.bak
expect_exit 0 "$MJ" update --dry-run
expect_grep '^update CLAUDE.md'
expect_no_grep '20m' CLAUDE.md
# over budget: nothing written, exit 10
sed -i.bak 's/always_loaded_budget_lines: 150/always_loaded_budget_lines: 10/' .majordomus/policy.yaml; rm -f .majordomus/policy.yaml.bak
expect_exit 10 "$MJ" update
expect_grep 'nothing written'
expect_no_grep '20m' CLAUDE.md
# unknown provider template
sed -i.bak 's/provider: gemini/provider: nosuch/' .majordomus/policy.yaml; rm -f .majordomus/policy.yaml.bak
sed -i.bak 's/always_loaded_budget_lines: 10/always_loaded_budget_lines: 150/' .majordomus/policy.yaml; rm -f .majordomus/policy.yaml.bak
expect_exit 12 "$MJ" update
expect_grep 'no template for provider'
