. "$ROOT/test/lib.sh"
# Proves the site is actually derived, not merely generated by a script that exits zero.
#
# A generator that ignored its inputs would pass every other check in this suite. This
# case copies the repository into a throwaway directory, changes one canonical value at a
# time, regenerates, and fails if the derived output did not change.

R="$T/repo"
mkdir -p "$R"
for p in bin lib share docs scripts test .majordomus README.md AGENTS.md; do
  cp -R "$ROOT/$p" "$R/"
done
mkdir -p "$R/site/data"
cp "$ROOT/site/config.toml" "$R/site/config.toml"
cp "$ROOT/site/data/marketing.toml" "$R/site/data/marketing.toml"
( cd "$R" && git init -q . && git config user.email t@example.com && git config user.name t \
  && git add -A >/dev/null 2>&1 && git commit -qm init ) || { echo "    fixture repo failed"; exit 1; }

gen() { ( cd "$R" && ./scripts/generate-site-data >/dev/null 2>&1 ); }
gen || { echo "    baseline generation failed"; exit 1; }
cp -R "$R/site/data/generated" "$T/baseline"

changed() { # file, description
  gen || { echo "    generation failed after changing $2"; exit 1; }
  if diff -r "$T/baseline" "$R/site/data/generated" >/dev/null 2>&1; then
    echo "    changing $2 did not change the derived site data — the site is not derived"
    exit 1
  fi
  cp -R "$R/site/data/generated" "$T/baseline.new" && rm -rf "$T/baseline" && mv "$T/baseline.new" "$T/baseline"
}

# 1. the version
sed 's/^MJ_VERSION=.*/MJ_VERSION="9.9.9"/' "$R/bin/majordomus" > "$R/b.tmp" && mv "$R/b.tmp" "$R/bin/majordomus" && chmod +x "$R/bin/majordomus"
changed bin/majordomus "the version in bin/majordomus"
grep -q '"version": "9.9.9"' "$R/site/data/generated/project.json" || { echo "    the new version did not reach project.json"; exit 1; }

# 2. a responsibility's prose, which lives in the README and nowhere else
sed 's/^| \*\*Watch\*\* | reports drift/| **Watch** | REPHRASED reports drift/' "$R/README.md" > "$R/r.tmp" && mv "$R/r.tmp" "$R/README.md"
changed README.md "a row of the README table"
grep -q 'REPHRASED' "$R/site/data/generated/responsibilities.json" || { echo "    the README edit did not reach responsibilities.json"; exit 1; }

# 3. a profile axis
sed 's/^effort: .*/effort: low/' "$R/.majordomus/profiles/debugging.yaml" > "$R/p.tmp" && mv "$R/p.tmp" "$R/.majordomus/profiles/debugging.yaml"
changed .majordomus/profiles/debugging.yaml "a profile axis"

# 4. a vocabulary term — one new row is one new routable page
printf '| **newterm** | an added concept | `nowhere` |\n' >> "$T/row"
awk '/^\| \*\*presentation\*\*/ { print; print "| **newterm** | an added concept | `nowhere` |"; next } { print }' \
  "$R/docs/CONCEPTS.md" > "$R/c.tmp" && mv "$R/c.tmp" "$R/docs/CONCEPTS.md"
changed docs/CONCEPTS.md "a row of the vocabulary table"
grep -q '"slug": "newterm"' "$R/site/data/generated/concepts.json" || { echo "    the new term did not reach concepts.json"; exit 1; }
[ -f "$R/site/content/concepts/newterm.md" ] || { echo "    the new term produced no routable page"; exit 1; }

# 5. the outcome vocabulary, read out of the code that enforces it
sed 's/case "$outcome" in completed|partial|blocked|no_match|failed)/case "$outcome" in completed|partial|blocked|no_match|failed|abandoned)/' \
  "$R/lib/finish.sh" > "$R/f.tmp" && mv "$R/f.tmp" "$R/lib/finish.sh"
changed lib/finish.sh "the outcome vocabulary in lib/finish.sh"
grep -q '"abandoned"' "$R/site/data/generated/lifecycle.json" || { echo "    the new outcome did not reach lifecycle.json"; exit 1; }

# 6. a claim: removing its implementation must fail the check, not produce a stale page
sed 's|    implementation: lib/watch.sh|    implementation: lib/gone.sh|' "$R/docs/CLAIMS.yaml" > "$R/cl.tmp" && mv "$R/cl.tmp" "$R/docs/CLAIMS.yaml"
if ( cd "$R" && ./scripts/generate-site-data --check >/dev/null 2>&1 ); then
  echo "    a claim naming a file that does not exist passed the check"
  exit 1
fi
