# majordomus-covers: none
# The merge policy claims a file only if a generator writes it.
#
# `merge=derived` resolves a merge to one side without a conflict marker and without a
# diagnostic. For a file a generator owns that is correct: the resolution is discarded a
# moment later when `scripts/derive` writes the real answer, and the `derived-current` gate
# refuses the commit until it does. For a file a *person* wrote it is silent data loss —
# one side's edit is gone and nothing anywhere says so.
#
# Case 57 proves the forward direction: every generated artifact carries the rule. This case
# proves the converse, which nothing did until 2026-09-12, and which was false in two ways at
# once on that date. `share/schemas/**/*.schema.json` claimed forty-five files of which the
# generator writes nine; `share/allow/**` claimed two allow-lists whose own first line reads
# "AUTHORED FILE — no generator derives it yet". Both ate real edits, and the second one ate
# the policy schema twice in one evening — the tree then refused to serve, with an error that
# named a missing schema key and nothing about a merge.
#
# The property is tested against the repository's own self-labelling rather than against the
# generator's implementation: a generated file here opens with "# GENERATED FILE", an authored
# one is required by convention not to. A case that recomputed the generator's own list would
# agree with it by construction and prove nothing.
. "$ROOT/test/lib.sh"

expect_file "$ROOT/.gitattributes"
expect_file "$ROOT/scripts/gitattributes"
[ -x "$ROOT/scripts/gitattributes" ] || { echo "    scripts/gitattributes is not executable"; exit 1; }

# ---------------------------------------------------------------- the converse
# Nothing that says it is authored may be claimed by the merge policy.
authored="$(git -C "$ROOT" grep -l -i '^# AUTHORED FILE' -- share docs .ai 2>/dev/null || true)"
[ -n "$authored" ] || { echo "    no file self-labels as authored; this assertion would pass vacuously"; exit 1; }
claimed="$(printf '%s\n' "$authored" | xargs git -C "$ROOT" check-attr merge -- | grep 'merge: derived' | sed 's/: merge:.*//' || true)"
[ -z "$claimed" ] || {
  echo "    $(printf '%s\n' "$claimed" | wc -l | tr -d ' ') file(s) say they are authored and the merge policy claims them as generated;"
  echo "    a merge will discard one side of each without a conflict marker:"
  printf '%s\n' "$claimed" | sed 's/^/    | /'
  exit 1
}

# And the forward half of the same convention: a file that says it is generated must be
# claimed, or every integration conflicts on it over content no branch decides.
# A template carries the banner it *emits*, so it reads as generated while being a source.
# It says so precisely: the banner's own `Source:` line names the template's own path. That
# is the discriminator, rather than a list of exceptions that would go stale — and a template
# must keep conflicting honestly, because merging two edits of a source is what git is for.
generated=""
for f in $(git -C "$ROOT" grep -l '^# GENERATED FILE' -- share 2>/dev/null || true); do
  grep -q "Source:.*$f" "$ROOT/$f" 2>/dev/null && continue
  generated="$generated $f"
done
generated="$(printf '%s\n' $generated)"
[ -n "$generated" ] || { echo "    no file self-labels as generated; this assertion would pass vacuously"; exit 1; }
unclaimed="$(printf '%s\n' "$generated" | xargs git -C "$ROOT" check-attr merge -- | grep -v 'merge: derived' | sed 's/: merge:.*//' || true)"
[ -z "$unclaimed" ] || {
  echo "    $(printf '%s\n' "$unclaimed" | wc -l | tr -d ' ') file(s) say they are generated and carry no merge=derived rule:"
  printf '%s\n' "$unclaimed" | sed 's/^/    | /'
  exit 1
}

# ---------------------------------------------------------------- the block is current
run_quiet "$T/current.err" "$ROOT/scripts/gitattributes" --check > "$T/current.out" \
  || { echo "    .gitattributes is not what scripts/gitattributes writes (run: scripts/gitattributes)"; exit 1; }

# ---------------------------------------------------------------- and --check can fail
# A check that cannot refuse is not a check. The mutation goes inside the managed block, is
# proved to be refused, and is undone whatever happens.
GA="$ROOT/.gitattributes"
cp "$GA" "$T/gitattributes.orig"
restore() { cp "$T/gitattributes.orig" "$GA"; }
trap restore EXIT
awk '/^# <<< generated by scripts\/gitattributes <<</ { print "share/allow/commands.txt      merge=derived" } { print }' \
  "$T/gitattributes.orig" > "$GA"
cmp -s "$GA" "$T/gitattributes.orig" && { echo "    the mutation changed nothing; the rest of this assertion is vacuous"; exit 1; }
if "$ROOT/scripts/gitattributes" --check > "$T/mutated.out" 2> "$T/mutated.err"; then
  echo "    scripts/gitattributes --check accepted a block claiming a file no generator writes"
  exit 1
fi
restore
run_quiet "$T/restored.err" "$ROOT/scripts/gitattributes" --check > "$T/restored.out" \
  || { echo "    the block was not restored"; exit 1; }
