# majordomus-covers: none
# An architectural relationship is drawn, not typed — and the gate can tell the difference.
#
# The whole risk in `scripts/ci/diagram-check` is its classifier. A gate that catches real
# diagrams and nothing else is worth having; one that also catches the transcript of a
# command, a file listing, or a block quoting a generated header is one that people route
# around within a week, and then it protects nothing at all.
#
# So this case builds the blocks it has to tell apart, in a fixture of its own, rather than
# trusting what this repository happens to contain today:
#
#   caught      box art, arrows, a +---+ box, a bare fence drawing a flow
#   not caught  a mermaid block, a console transcript, a file tree, a tree whose
#               annotation contains an arrow, a block quoting an HTML comment
#
# The last two are the ones that look like false positives and are not: `# start → finish`
# on a tree line is a sentence, and `<!-- generated by … -->` is quoted file content.
#
# The same two questions are asked again of the HTML form — a `<pre>`/`<code>` block in a
# template or a page — because for its first weeks this gate read markdown fences only, and
# the most-published document in the repository is a template. An HTML block declares its
# language in a `class` or `data-lang` attribute, so `class="console"` is exactly as exempt
# as a ```console fence and a `<pre>` wearing only layout classes declares nothing.
. "$ROOT/test/lib.sh"
GATE="$ROOT/scripts/ci/diagram-check"
[ -x "$GATE" ] || { echo "    $GATE is not executable"; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "    python3 absent; skipping"; exit 0; }

S="$(mktemp -d "${TMPDIR:-/tmp}/mj-272.XXXXXX")"
trap 'rm -rf "$S"' EXIT

fixture() {  # fixture <dir>
  mkdir -p "$1/docs" "$1/site/content-src" "$1/site/templates" "$1/.ai/repo"
  printf 'diagrams=0\n' > "$1/.ai/repo/diagram-baseline.txt"
}

# The gate's own count, for a fixture. `--update` writes it where the gate reads it.
counted() {  # counted <fixture-dir>
  MJ_ROOT="$1" "$GATE" --update >/dev/null 2>&1
  sed -n 's/^diagrams=\([0-9]*\)$/\1/p' "$1/.ai/repo/diagram-baseline.txt"
}

# ---------------------------------------------------------------- what must be caught
D="$S/caught"; fixture "$D"
cat > "$D/docs/A.md" <<'MD'
# Box art is a diagram

```text
   ┌──────────┐        ┌──────────┐
   │ registry │ ──────▶│ surfaces │
   └──────────┘        └──────────┘
```
MD
cat > "$D/docs/B.md" <<'MD'
# A plain flow is a diagram

```text
  intent  -->  plan  -->  execute
```
MD
cat > "$D/docs/C.md" <<'MD'
# So is a plus-box, and a bare fence

```
+--------+
| thing  |
+--------+
```
MD
MJ_ROOT="$D" "$GATE" --update >/dev/null 2>&1
found="$(sed -n 's/^diagrams=\([0-9]*\)$/\1/p' "$D/.ai/repo/diagram-baseline.txt")"
[ "$found" = 3 ] || {
  echo "    the gate found $found of 3 hand-drawn diagrams:"
  MJ_ROOT="$D" "$GATE" --list; exit 1; }

# and with a baseline of zero it refuses, naming them
printf 'diagrams=0\n' > "$D/.ai/repo/diagram-baseline.txt"
expect_exit 10 env MJ_ROOT="$D" "$GATE"
expect_grep 'rose from 0 to 3'
expect_grep 'docs/A\.md'
expect_grep 'mermaid'

# ---------------------------------------------------------------- what must NOT be caught
N="$S/clean"; fixture "$N"
cat > "$N/docs/A.md" <<'MD'
# A mermaid block is the answer, not the problem

```mermaid
flowchart LR
  registry["registry"] --> surfaces["surfaces"]
```
MD
cat > "$N/docs/B.md" <<'MD'
# Literal terminal output is exempt by declaration

```console
$ majordomus release analyze
  implied       minor
  required      minor
  ──────────────────────
  next minimum  0.6.0
```
MD
cat > "$N/docs/C.md" <<'MD'
# A file listing is not an architecture

```text
.
├── bin/
│   └── majordomus
└── lib/
    └── common.sh
```
MD
cat > "$N/docs/D.md" <<'MD'
# A tree annotation is prose, arrow and all

```text
tests/
├── fixtures/
│   └── minimal/                 # a scratch repo walked through start → finish
└── run.sh
```
MD
cat > "$N/docs/E.md" <<'MD'
# Quoted file content is not an arrow

```markdown
<!-- generated by `majordomus update` from .ai/repo/policy.yaml — do not edit -->
# CLAUDE.md
```
MD
MJ_ROOT="$N" "$GATE" --update >/dev/null 2>&1
found="$(sed -n 's/^diagrams=\([0-9]*\)$/\1/p' "$N/.ai/repo/diagram-baseline.txt")"
[ "$found" = 0 ] || {
  echo "    the gate caught $found block(s) that are not diagrams:"
  MJ_ROOT="$N" "$GATE" --list; exit 1; }
expect_exit 0 env MJ_ROOT="$N" "$GATE"
expect_grep 'no hand-drawn diagram'

# --------------------------------------------------- the HTML form: what must be caught
# Box art typed into a template is the case this gate was blind to for its first weeks: the
# homepage carried a hand-drawn control loop inside a <pre>, and a parser that reads ``` only
# cannot see it however many roots it walks. Entity-encoded arrows count too — `--&gt;` is
# what an author writes when the page must survive the markup, and it renders as an arrow.
H="$S/html"; fixture "$H"
cat > "$H/site/templates/loop.html" <<'HTML'
<section>
  <div class="min-w-0 overflow-x-auto rounded-base border border-default" tabindex="0">
    <pre class="m-0 p-5 font-mono text-xs leading-relaxed text-heading sm:text-sm"><code>EXECUTE
  ↓
VERIFY ──────────┐
  ↓              │ not satisfied
PROOF            ▼
              REPLAN</code></pre>
  </div>
</section>
HTML
cat > "$H/site/content-src/flow.md" <<'MD'
# An HTML block in a page is a block too, entities and all

<pre><code>intent  --&gt;  plan  --&gt;  execute</code></pre>
MD
found="$(counted "$H")"
[ "$found" = 2 ] || {
  echo "    the gate found $found of 2 hand-drawn diagrams in HTML blocks:"
  MJ_ROOT="$H" "$GATE" --list; exit 1; }
printf 'diagrams=0\n' > "$H/.ai/repo/diagram-baseline.txt"
expect_exit 10 env MJ_ROOT="$H" "$GATE"
expect_grep 'rose from 0 to 2'
expect_grep 'site/templates/loop\.html'
expect_grep 'site/content-src/flow\.md'

# ----------------------------------------------- the HTML form: what must NOT be caught
# These are the ones that decide whether the gate survives. A `<pre class="console">` holding
# what a command printed, and a `<pre>` holding a file tree, are the two blocks a template
# author writes most often; catching either would make the gate something to route around.
C="$S/htmlclean"; fixture "$C"
cat > "$C/site/templates/transcript.html" <<'HTML'
<figure>
  <figcaption>majordomus release analyze</figcaption>
  <pre class="console m-0 p-4 font-mono text-xs"><code>$ majordomus release analyze
  implied       minor
  required      minor
  ──────────────────────
  next minimum  0.6.0
  → 0.6.0</code></pre>
</figure>
HTML
cat > "$C/site/templates/tree.html" <<'HTML'
<pre class="m-0 p-4 font-mono text-xs"><code>.
├── bin/
│   └── majordomus
└── lib/
    └── common.sh                # walked through start → finish</code></pre>
HTML
cat > "$C/site/templates/drawn.html" <<'HTML'
<pre class="mermaid m-0 bg-transparent font-mono text-xs">flowchart LR
    registry["registry"] --&gt; surfaces["surfaces"]</pre>
HTML
cat > "$C/site/templates/declared.html" <<'HTML'
<pre class="language-bash"><code>find . -name '*.md' | head -3
# a --&gt; b, said a shell comment</code></pre>
<p>Inline <code>a → b</code> is a word in a sentence, not a drawing.</p>
HTML
cat > "$C/site/content-src/quoted.md" <<'MD'
# Quoting the markup of a drawing is not drawing one

```html
<pre class="m-0 p-5"><code>VERIFY ──────────┐
  ↓              │ not satisfied
PROOF            ▼</code></pre>
```
MD
found="$(counted "$C")"
[ "$found" = 0 ] || {
  echo "    the gate caught $found HTML block(s) that are not diagrams:"
  MJ_ROOT="$C" "$GATE" --list; exit 1; }
expect_exit 0 env MJ_ROOT="$C" "$GATE"
expect_grep 'no hand-drawn diagram'

# ------------------------------------------- a block inside a fence is one block, not two
# A Markdown page may fence a block of HTML that is itself a drawing. It is one finding: the
# fence parser sees it, and the HTML parser must not see it again through the same bytes.
O="$S/once"; fixture "$O"
cat > "$O/site/content-src/once.md" <<'MD'
# One drawing, written twice over

```text
<pre><code>a ──▶ b</code></pre>
```
MD
found="$(counted "$O")"
[ "$found" = 1 ] || {
  echo "    one drawing inside one fence was counted $found time(s):"
  MJ_ROOT="$O" "$GATE" --list; exit 1; }

# ---------------------------------------------------------------- the ratchet holds both ways
R="$S/ratchet"; fixture "$R"
cat > "$R/docs/A.md" <<'MD'
```text
  a --> b
```
MD
printf 'diagrams=1\n' > "$R/.ai/repo/diagram-baseline.txt"
expect_exit 0 env MJ_ROOT="$R" "$GATE"
expect_grep 'at the baseline'

# converting it must not pass silently against a baseline that still expects one
cat > "$R/docs/A.md" <<'MD'
```mermaid
flowchart LR
  a["a"] --> b["b"]
```
MD
expect_exit 10 env MJ_ROOT="$R" "$GATE"
expect_grep 'fell from 1 to 0'

# and a baseline that records the conversion is green again
printf 'diagrams=0\n' > "$R/.ai/repo/diagram-baseline.txt"
expect_exit 0 env MJ_ROOT="$R" "$GATE"

# ---------------------------------------------------------------- an absent baseline is unusable
U="$S/nobaseline"; mkdir -p "$U/docs"
expect_exit 12 env MJ_ROOT="$U" "$GATE"
expect_grep 'is missing'

# ---------------------------------------------------------- this repository is at its baseline
# The gate is run against the tree it ships in, so a conversion that lands without the
# baseline following it is caught here as well as in CI.
expect_exit 0 "$GATE"
