# majordomus-covers: none
# An architectural relationship is drawn, not typed — and the gate can tell the difference.
#
# The whole risk in `scripts/ci/diagram-check` is its classifier. A gate that catches real
# diagrams and nothing else is worth having; one that also catches the transcript of a
# command, a file listing, or a block quoting a generated header is one that people route
# around within a week, and then it protects nothing at all.
#
# So this case builds the blocks it has to tell apart, in a fixture of its own, rather than
# trusting what this repository happens to contain today:
#
#   caught      box art, arrows, a +---+ box, a bare fence drawing a flow
#   not caught  a mermaid block, a console transcript, a file tree, a tree whose
#               annotation contains an arrow, a block quoting an HTML comment
#
# The last two are the ones that look like false positives and are not: `# start → finish`
# on a tree line is a sentence, and `<!-- generated by … -->` is quoted file content.
. "$ROOT/test/lib.sh"
GATE="$ROOT/scripts/ci/diagram-check"
[ -x "$GATE" ] || { echo "    $GATE is not executable"; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "    python3 absent; skipping"; exit 0; }

S="$(mktemp -d "${TMPDIR:-/tmp}/mj-272.XXXXXX")"
trap 'rm -rf "$S"' EXIT

fixture() {  # fixture <dir>
  mkdir -p "$1/docs" "$1/.ai/repo"
  printf 'diagrams=0\n' > "$1/.ai/repo/diagram-baseline.txt"
}

# ---------------------------------------------------------------- what must be caught
D="$S/caught"; fixture "$D"
cat > "$D/docs/A.md" <<'MD'
# Box art is a diagram

```text
   ┌──────────┐        ┌──────────┐
   │ registry │ ──────▶│ surfaces │
   └──────────┘        └──────────┘
```
MD
cat > "$D/docs/B.md" <<'MD'
# A plain flow is a diagram

```text
  intent  -->  plan  -->  execute
```
MD
cat > "$D/docs/C.md" <<'MD'
# So is a plus-box, and a bare fence

```
+--------+
| thing  |
+--------+
```
MD
MJ_ROOT="$D" "$GATE" --update >/dev/null 2>&1
found="$(sed -n 's/^diagrams=\([0-9]*\)$/\1/p' "$D/.ai/repo/diagram-baseline.txt")"
[ "$found" = 3 ] || {
  echo "    the gate found $found of 3 hand-drawn diagrams:"
  MJ_ROOT="$D" "$GATE" --list; exit 1; }

# and with a baseline of zero it refuses, naming them
printf 'diagrams=0\n' > "$D/.ai/repo/diagram-baseline.txt"
expect_exit 10 env MJ_ROOT="$D" "$GATE"
expect_grep 'rose from 0 to 3'
expect_grep 'docs/A\.md'
expect_grep 'mermaid'

# ---------------------------------------------------------------- what must NOT be caught
N="$S/clean"; fixture "$N"
cat > "$N/docs/A.md" <<'MD'
# A mermaid block is the answer, not the problem

```mermaid
flowchart LR
  registry["registry"] --> surfaces["surfaces"]
```
MD
cat > "$N/docs/B.md" <<'MD'
# Literal terminal output is exempt by declaration

```console
$ majordomus release analyze
  implied       minor
  required      minor
  ──────────────────────
  next minimum  0.6.0
```
MD
cat > "$N/docs/C.md" <<'MD'
# A file listing is not an architecture

```text
.
├── bin/
│   └── majordomus
└── lib/
    └── common.sh
```
MD
cat > "$N/docs/D.md" <<'MD'
# A tree annotation is prose, arrow and all

```text
tests/
├── fixtures/
│   └── minimal/                 # a scratch repo walked through start → finish
└── run.sh
```
MD
cat > "$N/docs/E.md" <<'MD'
# Quoted file content is not an arrow

```markdown
<!-- generated by `majordomus update` from .ai/repo/policy.yaml — do not edit -->
# CLAUDE.md
```
MD
MJ_ROOT="$N" "$GATE" --update >/dev/null 2>&1
found="$(sed -n 's/^diagrams=\([0-9]*\)$/\1/p' "$N/.ai/repo/diagram-baseline.txt")"
[ "$found" = 0 ] || {
  echo "    the gate caught $found block(s) that are not diagrams:"
  MJ_ROOT="$N" "$GATE" --list; exit 1; }
expect_exit 0 env MJ_ROOT="$N" "$GATE"
expect_grep 'no hand-drawn diagram'

# ---------------------------------------------------------------- the ratchet holds both ways
R="$S/ratchet"; fixture "$R"
cat > "$R/docs/A.md" <<'MD'
```text
  a --> b
```
MD
printf 'diagrams=1\n' > "$R/.ai/repo/diagram-baseline.txt"
expect_exit 0 env MJ_ROOT="$R" "$GATE"
expect_grep 'at the baseline'

# converting it must not pass silently against a baseline that still expects one
cat > "$R/docs/A.md" <<'MD'
```mermaid
flowchart LR
  a["a"] --> b["b"]
```
MD
expect_exit 10 env MJ_ROOT="$R" "$GATE"
expect_grep 'fell from 1 to 0'

# and a baseline that records the conversion is green again
printf 'diagrams=0\n' > "$R/.ai/repo/diagram-baseline.txt"
expect_exit 0 env MJ_ROOT="$R" "$GATE"

# ---------------------------------------------------------------- an absent baseline is unusable
U="$S/nobaseline"; mkdir -p "$U/docs"
expect_exit 12 env MJ_ROOT="$U" "$GATE"
expect_grep 'is missing'

# ---------------------------------------------------------- this repository is at its baseline
# The gate is run against the tree it ships in, so a conversion that lands without the
# baseline following it is caught here as well as in CI.
expect_exit 0 "$GATE"
