# majordomus-covers: none
# claims: economics-claims-gated
# majordomus-timeout: 600
# `economics check` refuses what no evidence produced. A claim bound to a metric may be
# guaranteed only while the metric stands: context-selection-counted with no recorded
# measurement is refused, is accepted once the suite has been measured, and is refused again
# the moment a measured mechanism changes. A savings number typed into prose is refused with
# its file and the line its number starts on, a sentence hard-wrapped over two lines and a
# compound like "total-token" included; the same numbers in a generated report are the
# calculator's and are not, and "generated" is known by the generator's stamp on the first
# line, never by the directory or by a prose line that says "generated by". A guaranteed
# claim that says tokens go down and that no binding names is refused, and so is a claim id
# used twice. The total-token claim cannot be marked guaranteed while the verdict is not
# publishable, and declarations the check cannot read are a finding, never a clean result.
. "$ROOT/test/lib.sh"
RB="$(rust_bin)" || rust_bin_exit $?

R="$T/repo"
fixture_repo "$R" .ai/repo/benchmarks/economics test/fixtures/economics docs/CLAIMS.yaml >/dev/null
rm -rf "$R/.ai/repo/benchmarks/economics/runs"
git -C "$R" init -q .
git -C "$R" config user.email t@example.com
git -C "$R" config user.name t
git -C "$R" add -A >/dev/null
git -C "$R" commit -qm fixture >/dev/null
mj() { ( cd "$R" && MAJORDOMUS_SHARE="$R/share" "$RB" "$@" ); }
grep -q 'id: context-selection-counted' "$R/docs/CLAIMS.yaml" || { echo "    the fixture lost the bound claim"; exit 1; }
# the line of a claim's id, which is where a finding about the claim points
id_line() { grep -n -- "- id: $1\$" "$R/docs/CLAIMS.yaml" | cut -d: -f1 | sed -n "${2:-1}p"; }

# a guaranteed claim with no evidence behind it
expect_exit 10 mj economics check
expect_grep "FAIL claim_unsupported +docs/CLAIMS.yaml:$(id_line context-selection-counted) — claim context-selection-counted is guaranteed, but its metric context_reduction_ratio is not_measured"

# measured: the guarantee stands
expect_exit 0 mj economics measure
expect_exit 0 mj economics check
expect_grep '0 finding\(s\)'

# a savings number typed by hand is refused where it stands: on its own line, in a sentence
# hard-wrapped over two lines (reported on the line the number starts on, not the line the
# sentence starts on), and after a compound whose only economics word is inside it
printf '%s\n' '# Pitch' '' 'With Majordomus a session spends 40% fewer tokens.' '' \
  'The compiler cuts the context a session' 'loads by 35% on every task.' '' \
  'It lowers total-token use by 25%.' > "$R/docs/PITCH.md"
git -C "$R" add docs/PITCH.md
expect_exit 10 mj economics check
expect_grep 'FAIL unsupported_quantity +docs/PITCH.md:3 — 40% next to the economics vocabulary'
expect_grep 'FAIL unsupported_quantity +docs/PITCH.md:6 — 35% next to the economics vocabulary'
expect_grep 'FAIL unsupported_quantity +docs/PITCH.md:8 — 25% next to the economics vocabulary'
expect_no_grep 'docs/PITCH.md:5 '
expect_grep '3 finding\(s\)'

# ... the directory a file sits in does not make it generated: a report under docs/generated/
# that no manifest lists and no generator stamped is hand-written and is scanned
mkdir -p "$R/docs/generated"
git -C "$R" mv docs/PITCH.md docs/generated/pitch.md
expect_exit 10 mj economics check
expect_grep 'FAIL unsupported_quantity +docs/generated/pitch.md:3 — 40%'
# ... and with its generator's stamp on the first line the same sentences are the
# calculator's, not a claim
{ printf '<!-- generated by majordomus economics -->\n'; cat "$R/docs/generated/pitch.md"; } > "$T/pitch.md"
mv "$T/pitch.md" "$R/docs/generated/pitch.md"
git -C "$R" add docs/generated/pitch.md
expect_exit 0 mj economics check

# a hand-written file whose prose says "generated by" below its first line is hand-written
printf '%s\n' '# Notes' '' 'This page was generated by hand, not by a generator.' \
  'It saves 40% of the tokens a session spends.' > "$R/docs/NOTES.md"
git -C "$R" add docs/NOTES.md
expect_exit 10 mj economics check
expect_grep 'FAIL unsupported_quantity +docs/NOTES.md:4 — 40%'
git -C "$R" rm -qf docs/NOTES.md
expect_exit 0 mj economics check

# a change to a measured mechanism makes the evidence stale, and the guarantee goes with it
printf '# touched\n' >> "$R/.ai/repo/knowledge/sources.yaml"
expect_exit 10 mj economics check
expect_grep 'context-selection-counted is guaranteed'
expect_exit 0 mj economics summary
expect_grep 'context +context +stale'
git -C "$R" checkout -q -- .ai/repo/knowledge/sources.yaml
expect_exit 0 mj economics check

# a guaranteed claim that says tokens go down, under an id no binding names, is refused, and
# a claim id used twice is refused where its second copy stands
cp "$R/docs/CLAIMS.yaml" "$T/CLAIMS.yaml"
cat >> "$R/docs/CLAIMS.yaml" <<'EOF'

  - id: sessions-spend-less
    claim: A session run under Majordomus spends fewer tokens than the same session run without it
    source: docs/ECONOMICS.md
    implementation: '-'
    test: '-'
    status: guaranteed
    responsibility: none

  - id: sessions-spend-less
    claim: The same claim, written down twice
    source: docs/ECONOMICS.md
    implementation: '-'
    test: '-'
    status: planned
    responsibility: none
EOF
expect_exit 10 mj economics check
expect_grep "FAIL claim_unbound +docs/CLAIMS.yaml:$(id_line sessions-spend-less 1) — claim sessions-spend-less is guaranteed and says tokens, context or cost go down"
expect_grep "FAIL claim_duplicate +docs/CLAIMS.yaml:$(id_line sessions-spend-less 2) — claim id sessions-spend-less appears more than once"
cp "$T/CLAIMS.yaml" "$R/docs/CLAIMS.yaml"
expect_exit 0 mj economics check

# the total-token claim cannot be promoted by editing its status
sed -i.bak '/id: token-savings-measured/,/status:/ s/status: planned/status: guaranteed/' "$R/docs/CLAIMS.yaml" && rm -f "$R/docs/CLAIMS.yaml.bak"
grep -A6 'id: token-savings-measured' "$R/docs/CLAIMS.yaml" | grep -q 'status: guaranteed' || { echo "    the promotion did not apply"; exit 1; }
expect_exit 10 mj economics check
expect_grep 'claim token-savings-measured is guaranteed, but its metric effective_token_reduction is not_measured and must be verified'
cp "$T/CLAIMS.yaml" "$R/docs/CLAIMS.yaml"

# declarations the check cannot read fail it closed: nothing can be shown to stand
cp "$R/.ai/repo/benchmarks/economics/methodology.yaml" "$T/methodology.yaml"
printf 'schema: economics-methodology/v1\n' > "$R/.ai/repo/benchmarks/economics/methodology.yaml"
expect_exit 10 mj economics check
expect_grep 'FAIL declarations_unreadable +\.ai/repo/benchmarks/economics'
cp "$T/methodology.yaml" "$R/.ai/repo/benchmarks/economics/methodology.yaml"
expect_exit 0 mj economics check
