# Mutation propagation. Consistency between surfaces is worth nothing if the surfaces are
# consistently stale, so each mutation below changes exactly one canonical fact and every
# surface has to move with it. A surface that does not move is a surface holding its own copy.
. "$ROOT/test/lib.sh"
# Every surface has to read the same fixture, and the site generator reads the repository it
# lives in, so the case runs against its own copy of the tool rather than against this one.
mkdir -p "$T/tool"
cp -R "$ROOT/bin" "$ROOT/lib" "$ROOT/share" "$ROOT/docs" "$ROOT/scripts" "$ROOT/site" "$T/tool/"
cp "$ROOT/README.md" "$ROOT/LICENSE" "$T/tool/"
rm -rf "$T/tool/site/public"
cd "$T/tool" || exit 1
git init -q .; git config user.email t@example.com; git config user.name t; git commit -q --allow-empty -m init
MJ="$T/tool/bin/majordomus"
SYNC="$T/tool/scripts/github-sync"
GEN="$T/tool/scripts/generate-site-data"
"$MJ" init >/dev/null
pj_init
pj_milestone M000
pj_issue I0001 M000
pj_issue I0002 M000
pj_issue I0003 M000 I0002
expect_exit 0 "$MJ" plan validate

snapshot() { # every surface, in one string
  "$MJ" plan list
  "$MJ" plan waves
  "$MJ" plan graph
  "$MJ" --json plan status
  "$MJ" plan body I0001
  "$SYNC" --plan
}
w() { "$MJ" plan list | awk -v i="$1" '$1==i{print $3}'; }
moved() { # label, before, after
  [ "$2" != "$3" ] || { printf '    %s: a canonical change moved no surface\n' "$1"; exit 1; }
}
unchanged() { # label, before, after
  [ "$2" = "$3" ] || { printf '    %s: a surface moved when nothing canonical did\n' "$1"; exit 1; }
}

# --- the control: generating twice from the same input produces the same output
A="$(snapshot)"; B="$(snapshot)"
unchanged "determinism" "$A" "$B"

# ---------------------------------------------------------------- mutation 1: one edge
# I0001 gains a dependency on I0002. Its status, its wave, the diagram, the projection and
# the milestone's counts must all change together.
before_status="$(pj_status I0001)"; before_wave="$(w I0001)"
before_graph="$("$MJ" plan graph)"; before_sync="$("$SYNC" --plan)"
before_waves="$("$MJ" plan waves)"; before_counts="$("$MJ" --json plan status)"
before_body="$("$MJ" plan body I0001)"
printf 'depends_on:\n  - I0002\n' >> .majordomus/project/issues/I0001.yaml
expect_exit 0 "$MJ" plan validate
[ "$before_status" = READY ] || { echo "    the fixture did not start from READY"; exit 1; }
[ "$(pj_status I0001)" = BLOCKED ] || { echo "    adding a dependency did not block the issue"; exit 1; }
moved "wave"                "$before_wave"   "$(w I0001)"
moved "Mermaid"             "$before_graph"  "$("$MJ" plan graph)"
moved "GitHub projection"   "$before_sync"   "$("$SYNC" --plan)"
moved "waves"               "$before_waves"  "$("$MJ" plan waves)"
moved "milestone counts"    "$before_counts" "$("$MJ" --json plan status)"
moved "the projection body" "$before_body"   "$("$MJ" plan body I0001)"
# the new edge is in the diagram and in the body, not only in the status
"$MJ" plan graph | grep -q 'I0002 --> I0001' || { echo "    the new edge is not in the diagram"; exit 1; }
"$MJ" plan body I0001 | grep -q 'I0002' || { echo "    the new edge is not in the projection body"; exit 1; }
# and the site data, generated by a separate program in a separate process, moved too
if command -v jq >/dev/null 2>&1 && "$GEN" --out "$T/gen1" >/dev/null 2>&1; then
  jq -e '.issues[] | select(.id=="I0001") | .depends_on == ["I0002"]' "$T/gen1/plan.json" >/dev/null \
    || { echo "    the generated site data does not carry the new edge"; exit 1; }
fi

# ---------------------------------------------------------------- mutation 2: one lifecycle fact
# Completing the dependency unblocks the dependent everywhere, with nothing edited by hand.
before_next="$("$MJ" --json plan next)"
"$MJ" plan start I0002 >/dev/null
"$MJ" plan evidence I0002 --covers proof --type test --command "true" --result ok >/dev/null
"$MJ" plan "done" I0002 >/dev/null
[ "$(pj_status I0001)" = READY ] || { echo "    completing the dependency did not unblock the dependent"; exit 1; }
[ "$(pj_status I0003)" = READY ] || { echo "    completing the dependency did not unblock I0003"; exit 1; }
moved "next ready issue" "$before_next" "$("$MJ" --json plan next)"
"$SYNC" --plan | grep -qE '^  I0002 +closed +DONE' || { echo "    a DONE issue is still open in the projection"; exit 1; }

# ---------------------------------------------------------------- mutation 3: one evidence record
# Removing the evidence takes the issue back to VERIFY. Completion is a derived fact, so it
# cannot survive the disappearance of the thing that justified it.
sed '/^evidence:/,$d' .majordomus/project/issues/I0002.yaml > "$T/i.yaml" && mv "$T/i.yaml" .majordomus/project/issues/I0002.yaml
[ "$(pj_status I0002)" = VERIFY ] || { echo "    removing the evidence left the issue DONE; the gate is decorative"; exit 1; }
[ "$(pj_status I0001)" = BLOCKED ] || { echo "    the dependent did not re-block when its dependency stopped being done"; exit 1; }
"$SYNC" --plan | grep -qE '^  I0002 +open +VERIFY' || { echo "    the projection still reports the issue closed"; exit 1; }

# ---------------------------------------------------------------- mutation 4: one acceptance criterion
# A change with no effect on the graph must still reach the surfaces that render prose.
before_body="$("$MJ" plan body I0003)"; before_wave3="$(w I0003)"
sed 's/^  - The work is done$/  - The work is done and reviewed/' .majordomus/project/issues/I0003.yaml > "$T/i.yaml" \
  && mv "$T/i.yaml" .majordomus/project/issues/I0003.yaml
moved "the projection body for a prose change" "$before_body" "$("$MJ" plan body I0003)"
unchanged "the wave for a prose change" "$before_wave3" "$(w I0003)"
"$MJ" plan body I0003 | grep -q 'done and reviewed' || { echo "    the changed criterion is not in the body"; exit 1; }

# ---------------------------------------------------------------- mutation 5: the graph becomes illegal
# The failure has to reach the exit code of every command that claims to validate the model.
printf 'depends_on:\n  - I0001\n' >> .majordomus/project/issues/I0002.yaml
expect_exit 10 "$MJ" plan validate
expect_grep 'dependency cycle'
# doctor exits 12 in this fixture because the copied tool has no projections or hooks
# installed; what matters here is that the graph failure is among its findings and that
# watch reports the same violation as drift.
expect_exit 12 "$MJ" doctor
expect_grep 'FAIL dag'
expect_grep 'dependency cycle'
expect_exit 11 "$MJ" watch
expect_grep 'DRIFT dag'
"$GEN" --out "$T/gen2" >/dev/null 2>&1 \
  && jq -e '[.findings[] | select(.level=="FAIL")] | length > 0' "$T/gen2/plan.json" >/dev/null \
  || true

# ---------------------------------------------------------------- mutation 6: one milestone edge
# The roadmap graph is a second graph over the same model, so it needs its own propagation
# proof: one edge between milestones has to move the roadmap sequence, the roadmap diagram,
# the gate and the GitHub projection, and it must not be satisfiable by finishing work.
rm -f .majordomus/project/issues/I0002.yaml   # undo mutation 5; the model is legal again
pj_issue I0002 M000
expect_exit 0 "$MJ" plan validate

rm_milestone() { # ID VERSION ORDER [DEP ...]
  local id="$1" ver="$2" ord="$3"; shift 3
  { cat <<Y
id: $id
title: Milestone $id
slug: $id
version: "$ver"
order: $ord
priority: p1
problem: "A problem worth solving."
outcome: "The outcome once it is solved."
acceptance_criteria:
  - The outcome is reached
validation:
  - true
evidence_required:
  - proof
Y
    if [ $# -gt 0 ]; then printf 'depends_on:\n'; for d in "$@"; do printf -- '  - %s\n' "$d"; done; fi
  } > ".majordomus/project/milestones/$id.yaml"
}
rmsnap() { "$MJ" plan roadmap; "$MJ" plan rgraph; "$MJ" --json plan roadmap; "$SYNC" --plan; }
mstat()  { "$MJ" plan roadmap | awk -v i="$1" '$3==i{print $2}'; }

# a second milestone with no dependency: reachable, and the roadmap shows it
before_rm="$(rmsnap)"
rm_milestone LATER 0.2 20
expect_exit 0 "$MJ" plan validate
moved "adding a milestone" "$before_rm" "$(rmsnap)"
[ "$(mstat LATER)" = PLANNED ] || { echo "    a milestone with no dependency is $(mstat LATER), expected PLANNED"; exit 1; }

# now one edge, and one edge only: LATER requires M000, which is not DONE
before_edge="$(rmsnap)"
before_gh="$("$SYNC" --plan)"
printf 'depends_on:\n  - M000\n' >> .majordomus/project/milestones/LATER.yaml
expect_exit 0 "$MJ" plan validate
moved "one milestone edge" "$before_edge" "$(rmsnap)"
moved "one milestone edge, in the GitHub projection" "$before_gh" "$("$SYNC" --plan)"
[ "$(mstat LATER)" = BLOCKED ] || { echo "    LATER is $(mstat LATER) behind an unfinished M000, expected BLOCKED"; exit 1; }
"$MJ" plan rgraph | grep -q 'M000 --> LATER' || { echo "    the milestone edge is not in the roadmap diagram"; exit 1; }
[ "$("$MJ" --json plan roadmap | jq -r '.milestones[]|select(.id=="LATER")|.blocked_by[0]')" = M000 ] \
  || { echo "    the JSON does not name what blocks LATER"; exit 1; }

# the gate is not satisfiable by finishing work inside the blocked milestone
pj_issue W1 LATER
"$MJ" plan start W1 >/dev/null || true
"$MJ" plan verify W1 >/dev/null || true
"$MJ" plan evidence W1 --covers proof --type test --command true --result ok >/dev/null
expect_exit 0 "$MJ" plan 'done' W1
[ "$(mstat LATER)" = BLOCKED ] \
  || { echo "    finishing every issue carried LATER past an unmet dependency; the gate is not a gate"; exit 1; }
# Work finished inside a milestone that is not reachable yet is a contradiction, not a
# state to display: the model is invalid until either the dependency is met or the work
# is not claimed as complete.
expect_exit 10 "$MJ" plan validate
expect_grep 'milestone_premature'

# Withdrawing the premature claim restores a legal model. A transition is refused while the
# model is invalid, which is itself the gate doing its job: no work may be recorded inside a
# contradiction.
expect_exit 15 "$MJ" plan start I0001
expect_grep 'BLOCKED, not READY'
rm -f .majordomus/project/issues/W1.yaml
expect_exit 0 "$MJ" plan validate

# completing the dependency releases it, with nothing edited by hand
before_release="$(rmsnap)"
# Earlier mutations left some of these part-way through their lifecycle, so each step is
# allowed to be a no-op; what matters is that all three end DONE.
for i in I0002 I0001 I0003; do
  "$MJ" plan start "$i"    >/dev/null 2>&1 || true
  "$MJ" plan verify "$i"   >/dev/null 2>&1 || true
  "$MJ" plan evidence "$i" --covers proof --type test --command true --result ok >/dev/null 2>&1 || true
  "$MJ" plan 'done' "$i"   >/dev/null 2>&1 || true
done
for i in I0002 I0001 I0003; do
  [ "$(pj_status "$i")" = DONE ] || { echo "    $i is $(pj_status "$i") after its full lifecycle, expected DONE"; exit 1; }
done
printf 'evidence:\n  - covers: proof\n    type: test\n    command: "true"\n    result: "ok"\n    recorded_at: 2026-09-04\n' \
  >> .majordomus/project/milestones/M000.yaml
[ "$(mstat M000)"  = DONE   ] || { echo "    M000 is $(mstat M000), expected DONE"; exit 1; }
[ "$(mstat LATER)" != BLOCKED ] || { echo "    LATER is still BLOCKED after its dependency reached DONE"; exit 1; }
moved "completing a milestone dependency" "$before_release" "$(rmsnap)"

# a milestone cycle is refused by every command that claims to validate the model
printf 'depends_on:\n  - LATER\n' >> .majordomus/project/milestones/M000.yaml
expect_exit 10 "$MJ" plan validate
expect_grep 'milestone_cycle'
expect_exit 12 "$MJ" doctor
expect_grep 'milestone dependencies form a cycle'
expect_exit 11 "$MJ" watch
