# Mutation propagation. Consistency between surfaces is worth nothing if the surfaces are
# consistently stale, so each mutation below changes exactly one canonical fact and every
# surface has to move with it. A surface that does not move is a surface holding its own copy.
. "$ROOT/test/lib.sh"
# Every surface has to read the same fixture, and the site generator reads the repository it
# lives in, so the case runs against its own copy of the tool rather than against this one.
mkdir -p "$T/tool"
cp -R "$ROOT/bin" "$ROOT/lib" "$ROOT/share" "$ROOT/docs" "$ROOT/scripts" "$ROOT/site" "$T/tool/"
cp "$ROOT/README.md" "$ROOT/LICENSE" "$T/tool/"
rm -rf "$T/tool/site/public"
cd "$T/tool" || exit 1
git init -q .; git config user.email t@example.com; git config user.name t; git commit -q --allow-empty -m init
MJ="$T/tool/bin/majordomus"
SYNC="$T/tool/scripts/github-sync"
GEN="$T/tool/scripts/generate-site-data"
"$MJ" init >/dev/null
pj_init
pj_milestone M000
pj_issue I0001 M000
pj_issue I0002 M000
pj_issue I0003 M000 I0002
expect_exit 0 "$MJ" plan validate

snapshot() { # every surface, in one string
  "$MJ" plan list
  "$MJ" plan waves
  "$MJ" plan graph
  "$MJ" --json plan status
  "$MJ" plan body I0001
  "$SYNC" --plan
}
w() { "$MJ" plan list | awk -v i="$1" '$1==i{print $3}'; }
moved() { # label, before, after
  [ "$2" != "$3" ] || { printf '    %s: a canonical change moved no surface\n' "$1"; exit 1; }
}
unchanged() { # label, before, after
  [ "$2" = "$3" ] || { printf '    %s: a surface moved when nothing canonical did\n' "$1"; exit 1; }
}

# --- the control: generating twice from the same input produces the same output
A="$(snapshot)"; B="$(snapshot)"
unchanged "determinism" "$A" "$B"

# ---------------------------------------------------------------- mutation 1: one edge
# I0001 gains a dependency on I0002. Its status, its wave, the diagram, the projection and
# the milestone's counts must all change together.
before_status="$(pj_status I0001)"; before_wave="$(w I0001)"
before_graph="$("$MJ" plan graph)"; before_sync="$("$SYNC" --plan)"
before_waves="$("$MJ" plan waves)"; before_counts="$("$MJ" --json plan status)"
before_body="$("$MJ" plan body I0001)"
printf 'depends_on:\n  - I0002\n' >> .majordomus/project/issues/I0001.yaml
expect_exit 0 "$MJ" plan validate
[ "$before_status" = READY ] || { echo "    the fixture did not start from READY"; exit 1; }
[ "$(pj_status I0001)" = BLOCKED ] || { echo "    adding a dependency did not block the issue"; exit 1; }
moved "wave"                "$before_wave"   "$(w I0001)"
moved "Mermaid"             "$before_graph"  "$("$MJ" plan graph)"
moved "GitHub projection"   "$before_sync"   "$("$SYNC" --plan)"
moved "waves"               "$before_waves"  "$("$MJ" plan waves)"
moved "milestone counts"    "$before_counts" "$("$MJ" --json plan status)"
moved "the projection body" "$before_body"   "$("$MJ" plan body I0001)"
# the new edge is in the diagram and in the body, not only in the status
"$MJ" plan graph | grep -q 'I0002 --> I0001' || { echo "    the new edge is not in the diagram"; exit 1; }
"$MJ" plan body I0001 | grep -q 'I0002' || { echo "    the new edge is not in the projection body"; exit 1; }
# and the site data, generated by a separate program in a separate process, moved too
if command -v jq >/dev/null 2>&1 && "$GEN" --out "$T/gen1" >/dev/null 2>&1; then
  jq -e '.issues[] | select(.id=="I0001") | .depends_on == ["I0002"]' "$T/gen1/plan.json" >/dev/null \
    || { echo "    the generated site data does not carry the new edge"; exit 1; }
fi

# ---------------------------------------------------------------- mutation 2: one lifecycle fact
# Completing the dependency unblocks the dependent everywhere, with nothing edited by hand.
before_next="$("$MJ" --json plan next)"
"$MJ" plan start I0002 >/dev/null
"$MJ" plan evidence I0002 --covers proof --type test --command "true" --result ok >/dev/null
"$MJ" plan "done" I0002 >/dev/null
[ "$(pj_status I0001)" = READY ] || { echo "    completing the dependency did not unblock the dependent"; exit 1; }
[ "$(pj_status I0003)" = READY ] || { echo "    completing the dependency did not unblock I0003"; exit 1; }
moved "next ready issue" "$before_next" "$("$MJ" --json plan next)"
"$SYNC" --plan | grep -qE '^  I0002 +closed +DONE' || { echo "    a DONE issue is still open in the projection"; exit 1; }

# ---------------------------------------------------------------- mutation 3: one evidence record
# Removing the evidence takes the issue back to VERIFY. Completion is a derived fact, so it
# cannot survive the disappearance of the thing that justified it.
sed '/^evidence:/,$d' .majordomus/project/issues/I0002.yaml > "$T/i.yaml" && mv "$T/i.yaml" .majordomus/project/issues/I0002.yaml
[ "$(pj_status I0002)" = VERIFY ] || { echo "    removing the evidence left the issue DONE; the gate is decorative"; exit 1; }
[ "$(pj_status I0001)" = BLOCKED ] || { echo "    the dependent did not re-block when its dependency stopped being done"; exit 1; }
"$SYNC" --plan | grep -qE '^  I0002 +open +VERIFY' || { echo "    the projection still reports the issue closed"; exit 1; }

# ---------------------------------------------------------------- mutation 4: one acceptance criterion
# A change with no effect on the graph must still reach the surfaces that render prose.
before_body="$("$MJ" plan body I0003)"; before_wave3="$(w I0003)"
sed 's/^  - The work is done$/  - The work is done and reviewed/' .majordomus/project/issues/I0003.yaml > "$T/i.yaml" \
  && mv "$T/i.yaml" .majordomus/project/issues/I0003.yaml
moved "the projection body for a prose change" "$before_body" "$("$MJ" plan body I0003)"
unchanged "the wave for a prose change" "$before_wave3" "$(w I0003)"
"$MJ" plan body I0003 | grep -q 'done and reviewed' || { echo "    the changed criterion is not in the body"; exit 1; }

# ---------------------------------------------------------------- mutation 5: the graph becomes illegal
# The failure has to reach the exit code of every command that claims to validate the model.
printf 'depends_on:\n  - I0001\n' >> .majordomus/project/issues/I0002.yaml
expect_exit 10 "$MJ" plan validate
expect_grep 'dependency cycle'
# doctor exits 12 in this fixture because the copied tool has no projections or hooks
# installed; what matters here is that the graph failure is among its findings and that
# watch reports the same violation as drift.
expect_exit 12 "$MJ" doctor
expect_grep 'FAIL dag'
expect_grep 'dependency cycle'
expect_exit 11 "$MJ" watch
expect_grep 'DRIFT dag'
"$GEN" --out "$T/gen2" >/dev/null 2>&1 \
  && jq -e '[.findings[] | select(.level=="FAIL")] | length > 0' "$T/gen2/plan.json" >/dev/null \
  || true
