# majordomus-covers: version
# The product version is authored in exactly one place — the `[package] version` of
# apps/majordomus-cli/Cargo.toml — and every other statement of it is derived and checked
# (ADR 0085, project.release-is-a-projection v2).
#
# The shell tool used to carry the version as a literal of its own, MJ_VERSION="…", which a
# check compared with the manifest and one writer rewrote beside it. It reads
# share/version.txt now: the manifest's projection, written by `majordomus generate`, shipped
# beside the tool in every archive, refused by `generate --check` when it falls behind. This
# case holds each half of that to what it claims:
#
#   1. bin/majordomus states no version at all;
#   2. what it prints is the authority;
#   3. it prints it because it reads the projection beside itself — generated from the
#      manifest, not from the executable's own constant, never read from MAJORDOMUS_SHARE,
#      and a missing projection is a refusal rather than a guess;
#   4. a projection edited by hand is refused by `generate --check`;
#   5. `release bump` writes the manifest's one line and the lock's own entry, and nothing
#      else — the projection is left to derivation;
#   6. a version written down by hand in lib/ is refused by the release module's diagnostic,
#      which is what the `version-authored-once` gate runs.
#
# Every section below was run, on its own, against the tree before this change, and failed
# there: the mutation fails before the fix passes.
. "$ROOT/test/lib.sh"
[ -f "$ROOT/apps/majordomus-cli/Cargo.toml" ] || { echo "    apps/majordomus-cli/Cargo.toml is missing"; exit 1; }
RB="$(rust_bin)" || rust_bin_exit $?
[ -x "$RB" ] || { echo "    the build produced no executable at $RB"; exit 1; }
S="$(mktemp -d "${TMPDIR:-/tmp}/mj-484.XXXXXX")"
trap 'rm -rf "$S"' EXIT
AUTHORITY="$("$ROOT/scripts/release-version")"
[ -n "$AUTHORITY" ] || { echo "    scripts/release-version read no version from the manifest"; exit 1; }

# ---------------------------------------------------------------- 1. the tool states no version
#
# Structural: no three-number literal anywhere in the file, comments included. The version
# the tool prints has to come from somewhere, and that somewhere may not be here.
if grep -nE '(^|[^0-9.])v?[0-9]+\.[0-9]+\.[0-9]+([^0-9.]|$)' "$ROOT/bin/majordomus" > "$S/literal"; then
  echo "    bin/majordomus states a version by hand:"; sed 's/^/      /' "$S/literal"; exit 1
fi

# ------------------------------------------------------------------------------- the fixture
# A repository that carries the tool and its crate: the tool, its libraries, its data and the
# one shell reader of the authority, beside a manifest that declares a version no build of
# this executable has — so that whatever states 4.5.6 below can only have read the manifest.
cp -R "$ROOT/bin" "$ROOT/lib" "$ROOT/share" .
mkdir -p apps/majordomus-cli scripts
cp "$ROOT/scripts/release-version" scripts/release-version
cat > apps/majordomus-cli/Cargo.toml <<'Y'
[package]
name = "majordomus-cli"
version = "4.5.6"
edition = "2021"

[dependencies]
decoy = { version = "4.5.6" }
Y
# The lock: this crate's entry, and a dependency that happens to be at the same version,
# which a writer that rewrote more than cargo would must leave alone.
cat > apps/majordomus-cli/Cargo.lock <<'Y'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "decoy"
version = "4.5.6"

[[package]]
name = "majordomus-cli"
version = "4.5.6"
dependencies = [
 "decoy",
]
Y
"$MJ" init >/dev/null
export MAJORDOMUS_SHARE="$PWD/share"

# ------------------------------------------------------------- 2. it prints the authority
# The projection is generated from the manifest, by the target that ships the distribution,
# and the tool prints exactly what the one shell reader reads from the manifest.
expect_exit 0 "$RB" generate distribution
expect_file share/version.txt
expect_grep '^# GENERATED FILE' share/version.txt
expect_grep '^version=4\.5\.6$' share/version.txt
[ "$(scripts/release-version)" = 4.5.6 ] || { echo "    the fixture's manifest does not read as 4.5.6"; exit 1; }
[ "$(bin/majordomus version)" = "majordomus $(scripts/release-version)" ] || {
  echo "    bin/majordomus prints '$(bin/majordomus version 2>&1)' and the manifest declares $(scripts/release-version)"
  exit 1; }
expect_exit 0 scripts/release-version --check
git add -A >/dev/null && git commit -qm "chore(fixture): a tree that carries the tool and its crate"
# and so does this checkout's own tool, against this checkout's own manifest
[ "$(env -u MAJORDOMUS_SHARE "$ROOT/bin/majordomus" version)" = "majordomus $AUTHORITY" ] || {
  echo "    bin/majordomus prints '$(env -u MAJORDOMUS_SHARE "$ROOT/bin/majordomus" version 2>&1)' and the manifest declares $AUTHORITY"
  exit 1; }

# ------------------------------------------- 3. it reads the projection, and only its own
# never from MAJORDOMUS_SHARE: that names data to read, not the identity of the reader
mkdir -p "$S/other/share"
printf 'version=9.9.9\n' > "$S/other/share/version.txt"
[ "$(MAJORDOMUS_SHARE="$S/other/share" bin/majordomus version)" = "majordomus 4.5.6" ] || {
  echo "    the tool took its version from MAJORDOMUS_SHARE"; exit 1; }

# and a distribution without its projection refuses, naming the file, rather than guessing
mv share/version.txt "$S/version.txt"
expect_exit 12 bin/majordomus version
expect_grep 'share/version\.txt states no version'
mv "$S/version.txt" share/version.txt
expect_exit 0 bin/majordomus version

# ---------------------------------------------------- 4. a hand-edited projection is refused
expect_exit 0 "$RB" generate distribution --check
sed 's/^version=.*/version=4.5.7/' share/version.txt > "$S/edited" && mv "$S/edited" share/version.txt
expect_exit 10 "$RB" generate distribution --check
expect_grep 'share/version\.txt'
# the same verdict from the version report, and the gate's code
expect_exit 10 "$RB" release version
expect_grep 'writers-disagree'
git checkout -- share/version.txt
expect_exit 0 "$RB" release version
expect_grep 'agree        yes'

# ------------------------------------------------ 5. the writer writes the one authored line
expect_exit 0 "$RB" release bump --exact 4.6.0
expect_grep 'apps/majordomus-cli/Cargo\.toml now declares 4\.6\.0'
expect_grep 'share/version\.txt and every generator stamp state 4\.6\.0 once scripts/derive has run'
git status --porcelain > "$S/status"
[ "$(cat "$S/status")" = " M apps/majordomus-cli/Cargo.lock
 M apps/majordomus-cli/Cargo.toml" ] || {
  echo "    the bump wrote more than the manifest and the lock:"; cat "$S/status"; exit 1; }
git diff --numstat > "$S/numstat"
while read -r added removed path; do
  [ "$added" = 1 ] && [ "$removed" = 1 ] || {
    echo "    the bump rewrote $path ($added added, $removed removed) instead of one line"; exit 1; }
done < "$S/numstat"
# the lock's line is the crate's own entry, never the dependency at the same version
git diff -U1 -- apps/majordomus-cli/Cargo.lock | grep -A2 '^ name = "majordomus-cli"$' | grep -q '^+version = "4.6.0"$' || {
  echo "    the lock line written is not the crate's own entry:"; git diff -- apps/majordomus-cli/Cargo.lock; exit 1; }
grep -q '^decoy = { version = "4.5.6" }$' apps/majordomus-cli/Cargo.toml || {
  echo "    a dependency pinned at the old version was rewritten in the manifest"; exit 1; }
# the projection is stale now, by design: a warning the writer can live with, which the
# derivation clears
expect_exit 10 "$RB" release version
expect_grep 'WARNING projection-stale'
expect_exit 0 "$RB" release bump --exact 4.6.0
expect_grep 'already 4\.6\.0'
expect_exit 0 "$RB" generate distribution
expect_grep '^version=4\.6\.0$' share/version.txt
expect_exit 0 "$RB" release version
git add -A >/dev/null && git commit -qm "chore(fixture): 4.6.0, derived"

# ------------------------------------------ 6. a version written down by hand is refused
mkdir -p lib
printf '#!/usr/bin/env bash\nFOO_VERSION="1.2.3"\n' > lib/extra.sh
expect_exit 10 "$RB" release version
expect_grep 'version-stated-by-hand'
expect_grep 'lib/extra\.sh:2 states a version by hand'
expect_grep 'apps/majordomus-cli/Cargo\.toml'
# the gate is this command, run the way .ai/repo/ci/gates.yaml runs it: through the launcher
expect_exit 10 env MAJORDOMUS_BIN="$RB" bin/majordomus-cli release version
expect_grep 'lib/extra\.sh:2'
rm lib/extra.sh
expect_exit 0 "$RB" release version
expect_no_grep 'version-stated-by-hand'
