# majordomus-exclusive: edits docs/PLAN_STATUS.md of this checkout and regenerates the derived files
# The committed derived artifacts match this repository's canonical files.
#
# Every other case that touches the generator runs it inside a fixture, which is right for
# testing what it produces and blind to whether what is committed here is current. Three CI
# steps depend on `generate-site-data --check` against this checkout, and until this case
# existed the local suite could be green while all three were red.
#
# It found a real defect the day it was written: docs/PLAN_STATUS.md recorded the commit it
# was generated at, so committing it made it name a commit that did not contain it, and
# --check reported drift on every commit for ever.
. "$ROOT/test/lib.sh"
command -v jq >/dev/null || { echo "    jq absent; skipping"; exit 0; }

# --- the committed generation is in sync with the canonical sources
expect_exit 0 "$ROOT/scripts/generate-site-data" --check
expect_grep 'site data: in sync'
# --- and so is every projection of the registry: the one gate over both generators, where the
#     executable can be built (the Rust suite and CI hold it where it cannot be skipped)
if command -v cargo >/dev/null 2>&1; then
  expect_exit 0 "$ROOT/scripts/derive-check"
  expect_grep 'every derived artifact is current'
fi

# --- and stays in sync across a commit. A derived artifact that records anything about the
#     commit it lands in is stale the moment it lands; regenerating cannot fix that, it only
#     moves the stale value forward. This is the property, not the symptom. source.json used
#     to be exempt: it carried the commit for the footer, so the generator was never idempotent
#     on a clean tree. The commit is now a fact of the build (site/data/build.json, written by
#     site-build and never committed), and no derived file is exempt.
for f in "$ROOT"/site/data/generated/*.json "$ROOT/docs/SITE_CLAIMS.md" "$ROOT/docs/PLAN_STATUS.md"; do
  [ -f "$f" ] || continue
  cur="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || true)"
  [ -n "$cur" ] || continue
  if grep -qF -- "${cur:0:7}" "$f"; then
    printf '    %s embeds the current commit; it will be stale the moment it is committed\n' "${f#"$ROOT"/}"
    exit 1
  fi
done

# --- every generated artifact says it is generated and names what it came from
for f in "$ROOT/docs/SITE_CLAIMS.md" "$ROOT/docs/PLAN_STATUS.md"; do
  [ -f "$f" ] || continue
  grep -qiE 'generated by|do not edit' "$f" || { printf '    %s carries no do-not-edit banner\n' "${f#"$ROOT"/}"; exit 1; }
done

# --- the derived plan document reports what the tool reports, from a separate process
if [ -f "$ROOT/docs/PLAN_STATUS.md" ]; then
  for id in $("$MJ" --repo "$ROOT" plan list | awk 'NR>1{print $1}'); do
    grep -qF "\`$id\`" "$ROOT/docs/PLAN_STATUS.md" || grep -qF "[$id]" "$ROOT/docs/PLAN_STATUS.md" \
      || { printf '    %s is in the model and not in docs/PLAN_STATUS.md\n' "$id"; exit 1; }
  done
  ready="$("$MJ" --repo "$ROOT" plan list | awk '$2=="READY"{print $1}')"
  for id in $ready; do
    awk '/^## Ready now/{f=1} f' "$ROOT/docs/PLAN_STATUS.md" | grep -qF "\`$id\`" \
      || { printf '    %s is READY and the derived document does not list it\n' "$id"; exit 1; }
  done
fi

# --- the canonical model of this repository validates, which is what CI gates on
expect_exit 0 "$MJ" --repo "$ROOT" plan validate

# --- the mutation: break the sync and the case must go red, or it proves nothing
printf "\n" >> "$ROOT/docs/PLAN_STATUS.md"
rc=0; "$ROOT/scripts/generate-site-data" --check >/dev/null 2>&1 || rc=$?
"$ROOT/scripts/generate-site-data" >/dev/null 2>&1
[ "$rc" = 10 ] || { echo "    --check did not report a hand edit to a generated document"; exit 1; }
expect_exit 0 "$ROOT/scripts/generate-site-data" --check
