# majordomus-covers: none
# majordomus-exclusive: edits fly.toml in this checkout to prove a hand edit is refused, then restores it
# The provider artifacts are projections of the deployment object, and only that.
#
# A hand-written Dockerfile and a hand-written fly.toml would restate the port, the routes,
# the resources and the build inputs the repository already knows, and every pair would
# drift the first time one half changed. So they are generated, they say so in their own
# first lines, and `generate --check` refuses a tree where one was edited.
#
# The case runs against this checkout's own deployment object, because that is the object
# whose projections are committed and whose drift would ship.
. "$ROOT/test/lib.sh"
RB="$(rust_bin)" || rust_bin_exit $?
MAJORDOMUS_SHARE="$ROOT/share"; export MAJORDOMUS_SHARE
W="$(mktemp -d "${TMPDIR:-/tmp}/mj86.XXXXXX")"; trap 'rm -rf "$W"' EXIT

# ---------------------------------------------------------------- the committed tree is current
"$RB" generate --repo "$ROOT" --check deployment >"$W/check.log" 2>&1 \
  || { echo "    the committed provider artifacts are stale:"; tail -3 "$W/check.log"; exit 1; }

# ---------------------------------------------------------------- each says what it is
for f in deploy/Dockerfile .dockerignore fly.toml; do
  [ -f "$ROOT/$f" ] || { echo "    $f was never generated"; exit 1; }
  head -4 "$ROOT/$f" | grep -q 'GENERATED by `majordomus generate deployment`' \
    || { echo "    $f does not say it is generated"; exit 1; }
  head -4 "$ROOT/$f" | grep -q '\.ai/repo/deployments/' \
    || { echo "    $f does not name the object it came from"; exit 1; }
done

# ---------------------------------------------------------------- one fact, three files
# The port is in the object; it must appear in the image definition and in the provider
# configuration because they were rendered from it, and nowhere as a literal somebody typed.
port="$(sed -n 's/^  port: \([0-9]*\)$/\1/p' "$ROOT/.ai/repo/deployments/majordomus.yaml")"
[ -n "$port" ] || { echo "    the object states no port"; exit 1; }
grep -q "^EXPOSE $port$" "$ROOT/deploy/Dockerfile" || { echo "    the image does not expose the declared port"; exit 1; }
grep -q "^internal_port = $port$" "$ROOT/fly.toml" || { echo "    the provider configuration does not use the declared port"; exit 1; }
# and the health routes the platform will poll are the ones the object names
for key in liveness readiness; do
  route="$(sed -n "s|^  $key: \(/.*\)$|\1|p" "$ROOT/.ai/repo/deployments/majordomus.yaml")"
  [ -n "$route" ] || { echo "    the object states no $key route"; exit 1; }
  grep -q "path = \"$route\"" "$ROOT/fly.toml" || { echo "    the provider configuration does not poll $route"; exit 1; }
done

# ---------------------------------------------------------------- the image carries no toolchain
grep -q '^FROM .* AS build$' "$ROOT/deploy/Dockerfile" || { echo "    the image is not multi-stage"; exit 1; }
grep -q '^USER ' "$ROOT/deploy/Dockerfile" || { echo "    the image runs as root"; exit 1; }
grep -q '^COPY --from=build ' "$ROOT/deploy/Dockerfile" || { echo "    the runtime stage does not take the binary from the builder"; exit 1; }
awk '/^FROM .* AS build$/{b=1} /^FROM [^ ]*$/{b=0} !b && /cargo|rustup|apk add/{print; found=1} END{exit found}' "$ROOT/deploy/Dockerfile" \
  || { echo "    the runtime stage carries a build toolchain"; exit 1; }
# nothing local, nothing secret
grep -qE '/Users/|/home/|_TOKEN|_SECRET|FlyV1|fo1_' "$ROOT/deploy/Dockerfile" "$ROOT/fly.toml" "$ROOT/.dockerignore" \
  && { echo "    a generated artifact carries an absolute developer path or a credential"; exit 1; }

# ---------------------------------------------------------------- the context is bounded
# Everything is excluded and the declared inputs are let back in, so a file that appears in
# the repository tomorrow does not appear in the image tomorrow.
# The first line that is not the generated banner must be `*`. Counting header lines was
# the same second statement of one fact this whole case exists to remove: the banner grew a
# line, `*` moved to the seventh, and a `head -6` window said the context was unbounded.
first="$(grep -vE '^[[:space:]]*(#|$)' "$ROOT/.dockerignore" | head -1)"
[ "$first" = '*' ] || { echo "    the ignore file does not exclude everything first (first rule: '$first')"; exit 1; }
grep -qx '\*\*/.git' "$ROOT/.dockerignore" || { echo "    the image would carry repository history"; exit 1; }
grep -qx '.ai/local' "$ROOT/.dockerignore" || { echo "    the image would carry the checkout-local half of the layer"; exit 1; }
for input in $(sed -n 's/^    - //p' "$ROOT/.ai/repo/deployments/majordomus.yaml"); do
  grep -qx "!$input" "$ROOT/.dockerignore" || { echo "    the build context does not carry the declared input $input"; exit 1; }
done

# ---------------------------------------------------------------- a hand edit is refused
cp "$ROOT/fly.toml" "$W/fly.toml.keep"
sed -i.bak 's/^memory_mb = .*/memory_mb = 4096/' "$ROOT/fly.toml"; rm -f "$ROOT/fly.toml.bak"
"$RB" generate --repo "$ROOT" --check deployment >"$W/edited.log" 2>&1 \
  && { cp "$W/fly.toml.keep" "$ROOT/fly.toml"; echo "    a hand edit to fly.toml was accepted"; exit 1; }
grep -q 'fly.toml (differs)' "$W/edited.log" \
  || { cp "$W/fly.toml.keep" "$ROOT/fly.toml"; echo "    the refusal did not name fly.toml"; exit 1; }
cp "$W/fly.toml.keep" "$ROOT/fly.toml"

# and regeneration puts it back exactly
"$RB" generate --repo "$ROOT" --check deployment >/dev/null 2>&1 \
  || { echo "    the tree was not restored"; exit 1; }
