# majordomus-covers: version
# Hand-written prose names no version label (project.prose-states-no-version).
#
# The limitations page said "What v0.1 does not do" while the site offered v0.13.0, and the
# list under it had gone stale with it. A label of two numbers names no release — releases
# are three — so it names the version the text was written about, and it stays where it was
# typed. `release version`, the command the `version-authored-once` gate runs, refuses it:
#
#   1. a label in hand-written prose is refused, with its file and line;
#   2. a released version named as the record it is (three numbers) is not a label, and
#      a generated page is not hand-written;
#   3. a document declared in the history, with a reason, may name its past version;
#   4. the history is held from both sides: an entry with no reason, one naming a path that
#      is not tracked prose, and one whose document carries no label any more are refused;
#   5. this repository's own prose is clean.
#
# Sections 1 and 5 were run against the tree before the rule and failed there: the fixture
# passed with its label, and this repository's prose carried them on public pages.
. "$ROOT/test/lib.sh"
[ -f "$ROOT/apps/majordomus-cli/Cargo.toml" ] || { echo "    apps/majordomus-cli/Cargo.toml is missing"; exit 1; }
RB="$(rust_bin)" || rust_bin_exit $?
[ -x "$RB" ] || { echo "    the build produced no executable at $RB"; exit 1; }

# ------------------------------------------------------------------------------- the fixture
# The product's layout, as far as the diagnosis needs it: a supervised repository, the
# manifest that makes it the product's, its projection, and prose.
mkdir -p apps/majordomus-cli share docs/generated site/content
printf '[package]\nname = "majordomus-cli"\nversion = "4.5.6"\n' > apps/majordomus-cli/Cargo.toml
printf 'version=4.5.6\n' > share/version.txt
printf '# Tool\n\nIt reads a policy. Release v0.3.1 was the first published.\n' > README.md
printf '# Design\n\nThe founding specification.\n' > docs/DESIGN.md
printf '+++\ntitle = "Limitations"\n+++\nWhat it does not do.\n' > site/content/limitations.md
"$MJ" init >/dev/null
# the distribution's data, which a fixture holding only share/version.txt would shadow
export MAJORDOMUS_SHARE="$ROOT/share"
git add -A >/dev/null && git commit -qm "chore(fixture): prose"
expect_exit 0 "$RB" release version || { echo "    a clean fixture was refused"; exit 1; }

# --------------------------------------------------------- 1. a label in prose is refused
printf '+++\ntitle = "Limitations"\ndescription = "What v0.1 does not do."\n+++\n' > site/content/limitations.md
printf '# Design\n\nThe v0.1 specification, as written then.\n' > docs/DESIGN.md
git add -A >/dev/null
expect_exit 10 "$RB" release version
expect_grep 'version-label-in-prose'
expect_grep 'site/content/limitations\.md:3 names the version it describes as `v0\.1`'
expect_grep 'docs/DESIGN\.md:3'
# through the launcher, the way .ai/repo/ci/gates.yaml runs the gate
cp -R "$ROOT/bin" "$ROOT/lib" .
expect_exit 10 env MAJORDOMUS_BIN="$RB" bin/majordomus-cli release version
expect_grep 'site/content/limitations\.md:3'
rm -rf bin lib

# ------------------------------------- 2. a release and a generated page are not labels
printf '+++\ntitle = "Limitations"\n+++\nWhat it does not do.\n' > site/content/limitations.md
printf '<!-- generated by majordomus economics -->\nAs of v0.2, nothing.\n' > docs/generated/report.md
git add -A >/dev/null
expect_exit 10 "$RB" release version
expect_no_grep 'README\.md'
expect_no_grep 'docs/generated/report\.md'
expect_no_grep 'limitations\.md'

# ----------------------------------------------- 3. a declared history may name its version
printf 'docs/DESIGN.md the founding specification of the design phase\n' > .ai/repo/version-label-history.txt
git add -A >/dev/null
expect_exit 0 "$RB" release version
expect_no_grep 'version-label-in-prose'
expect_no_grep 'version-label-history-invalid'

# ------------------------------------------------- 4. the history is held from both sides
printf 'docs/DESIGN.md\n' > .ai/repo/version-label-history.txt
expect_exit 10 "$RB" release version
expect_grep 'version-label-history-invalid'
expect_grep 'says nothing about why'
expect_grep 'docs/DESIGN\.md:3'

printf 'docs/DESIGN.md dated\ndocs/GONE.md it was removed\n' > .ai/repo/version-label-history.txt
expect_exit 10 "$RB" release version
expect_grep 'exempts docs/GONE\.md, which is not tracked hand-written prose'

printf 'docs/DESIGN.md dated\n' > .ai/repo/version-label-history.txt
printf '# Design\n\nThe founding specification.\n' > docs/DESIGN.md
expect_exit 10 "$RB" release version
expect_grep 'exempts docs/DESIGN\.md, which names no version label any more'

# ------------------------------------------------------- 5. this repository's prose is clean
cd "$ROOT"
expect_exit 0 "$RB" release version || {
  echo "    this repository's prose names a version label:"; printf '%s\n' "$LAST_OUT" | grep -E 'version-label-(in-prose|history-invalid)' | sed 's/^/      /'; exit 1; }
