//! The provider bootstraps are projections of the policy: `generate providers` writes
//! them, `--check` detects a hand edit or a stale render, and a declaration that cannot be
//! rendered is refused with the reason, not skipped.

mod common;

use common::{run_in, Fixture};

const STAMP_PREFIX: &str =
    "<!-- generated by `majordomus update` from .ai/repo/policy.yaml (policy ";

#[test]
fn provider_targets_are_written_checked_and_a_hand_edit_is_stale_until_regenerated() {
    let f = Fixture::new();
    let root = f.root();

    // 1. missing → stale, and check writes nothing
    let (code, _, err) = run_in(&root, &["generate", "providers", "--check"], "");
    assert_eq!(code, 10, "{err}");
    assert!(err.contains("AGENTS.md (missing)"), "{err}");
    assert!(!f.path("AGENTS.md").exists());

    // 2. generate writes the stamped file
    let (code, stdout, err) = run_in(&root, &["generate", "providers"], "");
    assert_eq!(code, 0, "{err}");
    assert!(stdout.contains("AGENTS.md"), "{stdout}");
    let first = std::fs::read_to_string(f.path("AGENTS.md")).unwrap();
    assert!(first.starts_with(STAMP_PREFIX), "{first}");
    assert!(
        first.contains("The default profile is\n`implementation`"),
        "tokens filled from the policy: {first}"
    );
    assert!(
        first.contains("checkpoint interval it sets is `15m`"),
        "{first}"
    );
    assert!(!first.contains("{{"), "no token left unfilled: {first}");

    // 3. check agrees, twice generates the same bytes
    let (code, stdout, _) = run_in(&root, &["generate", "providers", "--check"], "");
    assert_eq!(code, 0, "{stdout}");
    run_in(&root, &["generate", "providers"], "");
    assert_eq!(std::fs::read_to_string(f.path("AGENTS.md")).unwrap(), first);

    // 4. a hand edit is stale, is not rewritten by check, and is repaired by generate
    f.write("AGENTS.md", &format!("{first}\nMy private rule.\n"));
    let (code, _, err) = run_in(&root, &["generate", "providers", "--check"], "");
    assert_eq!(code, 10);
    assert!(err.contains("AGENTS.md (differs)"), "{err}");
    assert!(std::fs::read_to_string(f.path("AGENTS.md"))
        .unwrap()
        .contains("My private rule."));
    let (code, _, _) = run_in(&root, &["generate", "providers"], "");
    assert_eq!(code, 0);
    assert_eq!(std::fs::read_to_string(f.path("AGENTS.md")).unwrap(), first);

    // 5. a policy change changes the stamp and the content
    let policy = std::fs::read_to_string(f.path(".ai/repo/policy.yaml")).unwrap();
    f.write(
        ".ai/repo/policy.yaml",
        &policy.replace(
            "checkpoint_interval_default: 15m",
            "checkpoint_interval_default: 30m",
        ),
    );
    let (code, _, err) = run_in(&root, &["generate", "providers", "--check"], "");
    assert_eq!(code, 10, "{err}");
    let (code, _, _) = run_in(&root, &["generate", "providers"], "");
    assert_eq!(code, 0);
    let second = std::fs::read_to_string(f.path("AGENTS.md")).unwrap();
    assert_ne!(second, first);
    assert!(second.contains("`30m`"), "{second}");
    let stamp = |s: &str| s.lines().next().unwrap().to_string();
    assert_ne!(stamp(&second), stamp(&first), "the policy hash moved");

    // 6. the whole `generate --check` covers providers too: it is one pipeline
    let (code, _, err) = run_in(&root, &["generate", "--check"], "");
    assert_eq!(code, 10, "{err}");
    assert!(
        err.contains("openapi.json (missing)") && !err.contains("AGENTS.md"),
        "{err}"
    );
    let (code, _, err) = run_in(&root, &["generate"], "");
    assert_eq!(code, 0, "{err}");
    f.write("AGENTS.md", &format!("{second}tail\n"));
    let (code, stdout, err) = run_in(&root, &["generate", "--check"], "");
    assert_eq!(code, 10, "{stdout}");
    assert!(
        err.contains("AGENTS.md (differs)") && !err.contains("openapi.json"),
        "{err}"
    );
}

#[test]
fn a_repository_template_overrides_the_distribution_and_region_mode_keeps_the_host() {
    let f = Fixture::new();
    let root = f.root();
    f.write(
        ".ai/repo/policy.yaml",
        "version: 1

context:
  always_loaded_budget_lines: 150

profiles:
  default: implementation
  checkpoint_interval_default: 15m

projections:
  - provider: agents
    target: AGENTS.md
    always_loaded: true
  - provider: notes
    target: docs/NOTES.md
    mode: region
",
    );
    f.write(
        ".ai/repo/providers/notes.tmpl",
        "Profile {{DEFAULT_PROFILE}} from policy {{POLICY_SHA}}.\n",
    );
    f.write("docs/NOTES.md", "# My notes\n\nHand-written intro.\n");

    let (code, _, err) = run_in(&root, &["generate", "providers"], "");
    assert_eq!(code, 0, "{err}");
    let notes = std::fs::read_to_string(f.path("docs/NOTES.md")).unwrap();
    assert!(notes.starts_with("# My notes\n\nHand-written intro.\n\n<!-- majordomus:begin "));
    assert!(notes.contains("Profile implementation from policy "));
    assert!(notes.ends_with("<!-- majordomus:end -->\n"));

    // the host text outside the region is the human's; a change there is not drift
    let edited = notes.replace("Hand-written intro.", "Hand-written intro, revised.");
    f.write("docs/NOTES.md", &edited);
    let (code, _, err) = run_in(&root, &["generate", "providers", "--check"], "");
    assert_eq!(code, 0, "{err}");

    // a change inside the region is
    let tampered = edited.replace("Profile implementation", "Profile debugging");
    f.write("docs/NOTES.md", &tampered);
    let (code, _, err) = run_in(&root, &["generate", "providers", "--check"], "");
    assert_eq!(code, 10);
    assert!(err.contains("docs/NOTES.md (differs)"), "{err}");
    run_in(&root, &["generate", "providers"], "");
    assert_eq!(
        std::fs::read_to_string(f.path("docs/NOTES.md")).unwrap(),
        edited
    );

    // malformed markers are refused, never spliced over
    f.write("docs/NOTES.md", "# x\n<!-- majordomus:begin -->\nno end\n");
    let (code, _, err) = run_in(&root, &["generate", "providers"], "");
    assert_eq!(code, 10);
    assert!(
        err.contains("docs/NOTES.md") && err.contains("malformed"),
        "{err}"
    );
}

#[test]
fn declarations_that_cannot_be_rendered_are_refused_with_the_reason() {
    let f = Fixture::new();
    let root = f.root();
    let base = "version: 1

profiles:
  default: implementation
  checkpoint_interval_default: 15m

projections:
";
    // no template for the provider
    f.write(
        ".ai/repo/policy.yaml",
        &format!("{base}  - provider: nosuch\n    target: NOSUCH.md\n"),
    );
    let (code, _, err) = run_in(&root, &["generate", "providers", "--check"], "");
    assert_eq!(code, 10);
    assert!(
        err.contains("NOSUCH.md") && err.contains("provider 'nosuch' has no template"),
        "{err}"
    );

    // a token the policy cannot fill
    f.write(".ai/repo/providers/odd.tmpl", "{{PROFILE_TABLE}}\n");
    f.write(
        ".ai/repo/policy.yaml",
        &format!("{base}  - provider: odd\n    target: ODD.md\n"),
    );
    let (code, _, err) = run_in(&root, &["generate", "providers", "--check"], "");
    assert_eq!(code, 10);
    assert!(err.contains("PROFILE_TABLE"), "{err}");

    // a value the policy does not set
    f.write(
        ".ai/repo/policy.yaml",
        "version: 1\nprojections:\n  - provider: agents\n    target: AGENTS.md\n",
    );
    let (code, _, err) = run_in(&root, &["generate", "providers", "--check"], "");
    assert_eq!(code, 10);
    assert!(err.contains("DEFAULT_PROFILE"), "{err}");

    // a target outside the repository
    f.write(
        ".ai/repo/policy.yaml",
        &format!("{base}  - provider: agents\n    target: ../ESCAPE.md\n"),
    );
    let (code, _, err) = run_in(&root, &["generate", "providers"], "");
    assert_eq!(code, 10);
    assert!(err.contains("inside the repository"), "{err}");
    assert!(!root.parent().unwrap().join("ESCAPE.md").exists());

    // over the always-loaded budget
    f.write(
        ".ai/repo/policy.yaml",
        "version: 1\ncontext:\n  always_loaded_budget_lines: 3\nprofiles:\n  default: implementation\n  checkpoint_interval_default: 15m\nprojections:\n  - provider: agents\n    target: AGENTS.md\n    always_loaded: true\n",
    );
    let (code, _, err) = run_in(&root, &["generate", "providers"], "");
    assert_eq!(code, 10);
    assert!(err.contains("over the always_loaded budget of 3"), "{err}");
    assert!(!f.path("AGENTS.md").exists(), "nothing written on refusal");

    // an unknown projection key is a policy error
    f.write(
        ".ai/repo/policy.yaml",
        &format!("{base}  - provider: agents\n    target: AGENTS.md\n    colour: red\n"),
    );
    let (code, _, err) = run_in(&root, &["generate", "providers"], "");
    assert_eq!(code, 10);
    assert!(err.contains("policy") && err.contains("colour"), "{err}");
}
